### ISSUE TITLE
New Sunny Boy inverters are unknown

### ISSUE THREAD

**Issue by SBFspot** [SBFspot/SBFspot#186]
SBFspot gives an unknow inverter message.

0x00002467

The inverter type is the new SMA Sunny Boy 3.0 (SB 3.0-1AV-40)

#### This work item was migrated from CodePlex
CodePlex work item ID: '182'
Vote count: '1'

**Comment by SBFspot** [comment]
[SBF@14/08/2017]
See issue 179 for fix

**Comment by SBFspot** [comment]
**Issue closed by _SBF_ with comment**
See TagList_340.zip in 3.3.1 release

**Reason closed**
Fixed

**Comment by sbf-** [comment]
Fixed in V3.4.0
