### ISSUE TITLE
sbfspot 3.2.0 beta with Raspbian Stretch

### ISSUE THREAD

**Issue by cerberusde** [SBFspot/SBFspot#190]
I use sbfspot 3.2.0 beta with the Multigat. I have updated my system to Raspbian Stretch and now I get the following message.

/home/pi/sbfspot/SBFspot: error while loading shared libraries: libboost_date_time.so.1.55.0: cannot open shared object file: No such file or directory

In Stretch the libboost-date-time-dev 1.62.0.1+b4 is installed.

 regards, cerberusde

**Comment by sbf-** [comment]
You will need to recompile SBFspot and link with the new libraries

**Comment by cerberusde** [comment]
Sorry, but I do not know how that works.

**Comment by sbf-** [comment]
Well, you already did this before ;-)
`sudo make install_sqlite`
Just make sure you have installed all the dependencies (see documentation)

**Comment by cerberusde** [comment]
Thanks, now it works.
