### ISSUE TITLE
Where is the program located ?

### ISSUE THREAD

**Issue by pascal69480** [SBFspot/SBFspot#191]
Since the project was migrated to Github, I'm unable to find back the sources of the program.
Where are they located ?

**Comment by sbf-** [comment]
Have a look [here](https://github.com/SBFspot/SBFspot/releases)

**Comment by pascal69480** [comment]
Thank you for your answer, I'm very confused, I'm not used to this website !

**Comment by sbf-** [comment]
I understand - I was once again forced to move ;-)
I added a link on the wiki home page, together with latest documentation.
