### ISSUE TITLE
mysql connection is not working

### ISSUE THREAD

**Issue by flex2000** [SBFspot/SBFspot#192]
Hello, trying to get the data to be pushed in a remote mysql database. I configured all the right way  but everytime i get
Error: Can't open SQLite db [web409_SBFspot]: 'unable to open database file' . The database connection with php is working without any problem with the data

**Comment by sbf-** [comment]
It seems you have compiled for sqlite, not mysql. Error says: can't open sqlite db

**Comment by flex2000** [comment]
Thanks for that hint.. that helped a lot. Sorry for that stupid question. I'm not really good in linux :-) prefer the colored os with that colored DB

**Comment by sbf-** [comment]
No problem.
