### ISSUE TITLE
SBFSpot refuses to Auto Start on reboot

### ISSUE THREAD

**Issue by fritserasmus** [SBFspot/SBFspot#195]
So I installed "SBFspot_SRC_331_Linux_Win32.tar.gz" after my previous installation just stopped working :-(

I am unable to let this command run after reboot / power out
sudo /usr/local/bin/sbfspot.3/SBFspotUploadDaemon

I followed the steps in the manual and rechecked:
So this command works perfect if the pi was rebooted.
sudo /usr/local/bin/sbfspot.3/SBFspotUploadDaemon

I added the lines:

#Start SBFspotUploadDaemon
sudo /usr/local/bin/sbfspot.3/SBFspotUploadDaemon

in the /etc/rc.local  file, but when I reboot the Pi, no values are posted to PVOUTPUT

Only when I manually enter:   sudo /usr/local/bin/sbfspot.3/SBFspotUploadDaemon

the values start to appear in PVOUTPUT.

I have a brand new Raspberry Pi 3 - Model B with latest Rasbian installed.

Any pointers - please

**Comment by sbf-** [comment]
Do you have an exit command before start of daemon?

**Comment by fritserasmus** [comment]
Nope!

Thanks for that!.
I just edited the file.

I will reboot tomorrow morning to see if it started.


Thanks for your quick reply!!!.

Regards

Frits

**Comment by fritserasmus** [comment]
thanks: It works 100% now

**Comment by sbf-** [comment]
Nice to hear.
