### ISSUE TITLE
Continuous Monitoring

### ISSUE THREAD

**Issue by EckhardM** [SBFspot/SBFspot#197]
So far I see SBFspot is designed to run in defined intervalls but not continuously. The SMA Sunny Explorer provides the current power creation value continuously. Is it possible to catch the current value(s) with SBFspot continuously too?

**Comment by sbf-** [comment]
Related to #148 
No, this is a feature request for quite a long time.

**Comment by PjotrekSE** [comment]
I (think) I have a working solution in my SBFspot repository, although only for Linux, specifically tested in Raspberry Pi.
@sbf : See pm.

**Comment by sbf-** [comment]
See #318
