### ISSUE TITLE
verbose default level

### ISSUE THREAD

**Issue by EckhardM** [SBFspot/SBFspot#198]
In version 3.3.1 the default verbose level is not "2" as mentioned in the help.  It seems that the default is "0" because there is no output without -v.

**Comment by sbf-** [comment]
I re-read your comment and conclude this is by design.
When you omit -v there is no verbose output.
When you add -v, the default verbose level is 2, so -v and -v2 give the same result

**Comment by EckhardM** [comment]
ok, got it, thanks!
