### ISSUE TITLE
(Request) Is there a way to do a one off collection of all data stored in inverter?

### ISSUE THREAD

**Issue by SCUZNUTS** [SBFspot/SBFspot#199]
I have a bluetooth inverter setup, humming along for the past year but I would like to collect the older data from more than a year ago.
Is there a one off 'Collect Everything'?

**Comment by sbf-** [comment]
It depends on the inverter you have.
Daydata (every 5min) is kept for 62days
Monthdata (every day) is kept until ... (forever??) - Same for events
Spotdata is not recorded.
To get the older data, execute

> `SBFspot -ad62 -am15 -ae15 -sp0 -v`

**Comment by SCUZNUTS** [comment]
Device Class:     Solar Inverters
Device Type:      SB 5000TL-21

Connecting over bluetooth. Tried the above command, it does go back to 01/01/2017 but not further.
I grabbed a laptop and installed 'Sunny Explorer' from SMA and the month data does populate from back into 2013/14.
I've used that to export the data.

Any other command to try for SBFspot?
Otherwise all good to mark this closed.

**Comment by sbf-** [comment]
Well I thought it was obvious the 62 in -ad62 is for 62 days back, so the 15 in -am15 is for 15 months ;-)
The bigger the number, the mor you go back in time.
