### ISSUE TITLE
How to upgrade?

### ISSUE THREAD

**Issue by rucksman** [SBFspot/SBFspot#201]
I am running version 3.3.1 on a raspberry with the mysql database running on a different server in my home network. Now I want to move from this raspberry to another one and use version 3.4.0, and I want to use the exisiting mysql database. Is there an upgrade script oir whatever which updates the database? As far as I understood your modification history there are additional tables and fields in version 3.4.0 as well as modified data types.

**Comment by sbf-** [comment]
Only if you have an inverter with battery, you need the extra table/view as defined in `Update_340_MySQL.sql`
Issue #177 is fixed in code and doesn't need db update.
