### ISSUE TITLE
Can't install 3.4.0 on RPI - errors with make file

### ISSUE THREAD

**Issue by michaelvorst** [SBFspot/SBFspot#202]
Hi, 

Started with 3.4.0 on a new Pi, all good as per the guide until the following error when trying to do sudo make install_sqlite:

test -d /usr/local/bin/sbfspot.3/ || mkdir -p /usr/local/bin/sbfspot.3/
cp sqlite/bin/SBFspot /usr/local/bin/sbfspot.3/
cp: cannot stat 'sqlite/bin/SBFspot': No such file or directory
makefile:108: recipe for target 'install' failed
make: *** [install] Error 1

directory it's called from is as follows:

/home/pi/sbfspot.3/SBFspot-3.4.0/SBFspot

331 seems to get past this error OK.

**Comment by sbf-** [comment]
See #194 for fix
