### ISSUE TITLE
Unknown Inverter Type SB3.6-1AV-40

### ISSUE THREAD

**Issue by Itsmmai** [SBFspot/SBFspot#210]
Unknown Inverter Type. Report this issue at https://sbfspot.codeplex.com/workitem/list/basic with following info:           
0x00002468 and Inverter Type=SB3.6-1AV-40 809

**Comment by sbf-** [comment]
Related to #204 
Updated V3.3.1 with latest taglists.
Copy Taglistxx-xx.txt files to `/usr/local/bin/sbfspot.3`
