### ISSUE TITLE
Unable to Open SQlite Database

### ISSUE THREAD

**Issue by Rebo4n** [SBFspot/SBFspot#213]
/usr/local/bin/sbfspot.3/SBFspot -v -finq -nocsv
SBFspot V3.4.1
Yet another tool to read power production of SMA solar inverters
(c) 2012-2018, SBF (https://github.com/SBFspot/SBFspot)
Compiled for Linux (LE) 32 bit with SQLite support
Commandline Args: -v -finq -nocsv
Reading config '/usr/local/bin/sbfspot.3/SBFspot.cfg'
Tue Apr 17 08:09:56 2018: INFO: Starting...
sunrise: 04:45
sunset : 18:39
Connecting to 00:80:25:30:CE:79 (1/10)
Initializing...
SUSyID: 125 - SessionID: 929965793 (0x376E26E1)
SMA netID=01
SUSyID: 181 - SN: 304998930
BT Signal=76.9%
Logon OK
Local Host Time: 17/04/2018 08:09:58
Plant Time     : 17/04/2018 08:09:57 (-1 sec)
TZ offset      : 3600 sec - DST: On
Last Time Set  : 17/04/2018 07:41:56
Time was already adjusted today
SUSyID: 181 - SN: 304998930
Device Name:      STP 12000TL-20 930
Device Class:     Solar Inverters
Device Type:      STP 12000TL-20
Software Version: 02.53.02.R
Serial number:    304998930
SUSyID: 181 - SN: 304998930
Device Status:      Ok
SUSyID: 181 - SN: 304998930
Device Temperature: 45.0°C
SUSyID: 181 - SN: 304998930
GridRelay Status:      Closed
SUSyID: 181 - SN: 304998930
Pac max phase 1: 12000W
Pac max phase 2: 12000W
Pac max phase 3: 12000W
SUSyID: 181 - SN: 304998930
Energy Production:
	EToday: 1.271kWh
	ETotal: 31395.970kWh
	Operation Time: 7304.31h
	Feed-In Time  : 6797.67h
SUSyID: 181 - SN: 304998930
DC Spot Data:
	String 1 Pdc:   2.407kW - Udc: 481.38V - Idc:  5.001A
	String 2 Pdc:   1.188kW - Udc: 491.13V - Idc:  2.420A
SUSyID: 181 - SN: 304998930
AC Spot Data:
	Phase 1 Pac :   1.202kW - Uac: 245.30V - Iac:  4.903A
	Phase 2 Pac :   1.188kW - Uac: 244.02V - Iac:  4.868A
	Phase 3 Pac :   1.187kW - Uac: 244.05V - Iac:  4.864A
	Total Pac   :   3.577kW
SUSyID: 181 - SN: 304998930
Grid Freq. : 49.97Hz
SUSyID: 181 - SN: 304998930
Current Inverter Time: 17/04/2018 08:09:54
Inverter Wake-Up Time: 17/04/2018 04:41:42
Inverter Sleep Time  : 17/04/2018 08:09:57
[2018-04-17 08:09:59.741] Error: Can't open SQLite db [/home/pi/smadata/SBFspot.db]: 'unable to open database file'
********************
* ArchiveDayData() *
********************
startTime = 5AD53900 -> 17/04/2018 00:00:00
**********************
* ArchiveMonthData() *
**********************
startTime = 5AC0C9C0 -> 01/04/2018 12:00:00
Reading events: 2018-Apr-01
Tue Apr 17 08:10:00 2018: INFO: Done.

**Comment by sbf-** [comment]
It looks like db is not read/writable. What is the output of
`ls -al /home/pi/smadata`

**Comment by Rebo4n** [comment]
pi@raspberrypi:~/smatada $ ls -la
total 36
drwxr-xr-x  2 pi www-data  4096 Apr 17 07:40 .
drwxr-xr-x 25 pi pi        4096 Apr 19 08:17 ..
-rwxrwxrwx  1 pi www-data 26624 Apr 17 07:40 SBFspot.db

**Comment by sbf-** [comment]
There is a typo ;-)
It should be sma**data**, not sma**tada**

**Comment by Rebo4n** [comment]
Thank you
