### ISSUE TITLE
MonthData DB duplicates

### ISSUE THREAD

**Issue by MatteoVentura** [SBFspot/SBFspot#214]
Hey awesome work! 

Im just having some weird duplicates in my database. here's an example.
So I have 2 different transformers from who I fetch data.

![bug](https://user-images.githubusercontent.com/17535288/39005557-d586c5b4-4400-11e8-977d-64467c415405.png)

As you see it's the same, just 5-minute difference.

Crontab cfg:

![image](https://user-images.githubusercontent.com/17535288/39005717-3b4ec004-4401-11e8-87e2-7efed951cd0d.png)

Monthdata.sh cfg:

![image](https://user-images.githubusercontent.com/17535288/39005807-6c593f4e-4401-11e8-8e1d-67b53e2151fd.png)

Config: https://pastebin.com/mU536JTf

**Comment by sbf-** [comment]
That’s strange indeed. That was a bug in the past, and it was solved by deleting existing records for that month. In theory they should disappear while importing that month again.

**Comment by MatteoVentura** [comment]
Any tips ? What I can try ?

**Comment by sbf-** [comment]
Since monthdata is imported once every day, the duplicates should disappear automatically.

**Comment by MatteoVentura** [comment]
Yes,  I understand but why does it sometimes  take 21:55 and other times 22:00?



Verzonden van mijn Redmi Note 4
Op SBF <notifications@github.com>, schreef 23 apr. 2018 3:41 p.m.:

Since monthdata is imported once every day, the duplicates should disappear automatically.

**Comment by sbf-** [comment]
I really don't know, but this date/time is reported by your inverter. Maybe SBFspot should round these to the nearest hour.
