### ISSUE TITLE
start SBFspotUpload.service failed because the control process exited with error code.

### ISSUE THREAD

**Issue by peterjgithub** [SBFspot/SBFspot#215]
I don't really know where to search for fixing.
systemctl status SBFspotUpload.service returns:

SBFspotUpload.service - SBFspot Upload Daemon
   Loaded: loaded (/usr/local/bin/sbfspot.3/SBFspotUpload.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2018-04-28 12:03:23 CEST; 55s ago
  Process: 10340 ExecStart=/usr/local/bin/sbfspot.3/SBFspotUploadDaemon -p /run/sbfspotupload.pid 2>&1> /dev/null (code=exited, status=1/FAILURE)

Any suggestion where I can start?

using: Raspberry Pi 3 Model B+ installed with openHABianPi 

maybe interesting info:
I applied the default SBFspot installation instructions

with the exception that I created /etc/sbfspot (permissions: 755)
and choose this location for:

in /etc/sbfspot/SBFspot:
../SBFspot
../SBFspotUploadCommon
../SBFspotUploadDaemon
../SBFspotUploadService

in /etc/sbfspot/smadata
../2018/ZZtop-20180428.csv
../2018/ZZtop-Spot-20180428.csv
../SBFspot.db

I double checked all configs, they all seem to be adapted to this.

**Comment by peterjgithub** [comment]
I could resolve the issue.

'cd /etc/sbfspot/smadata
mkdir logs`  

Now it is working & generating logfiles.

I didn't close this issue, so that devs can evaluate if a fix is needed. Feel free to close it when this is considered.

**Comment by sbf-** [comment]
I'll leave it open for now.
Thinking about creating the log folder when it doesn't exist.
Thanks for reporting.

**Comment by sbf-** [comment]
IT seems like I left some buggy testcode in upload daemon of v3.4.1
I removed this release and come back later on this .

**Comment by sbf-** [comment]
Fixed in V3.5.0
