### ISSUE TITLE
Multiple SMA Bluetooth inverters

### ISSUE THREAD

**Issue by johnswinnen** [SBFspot/SBFspot#219]
Hello,

I have installed the SBFSpot tool on my PI but only 1 of my 3 SMA Inverters can communicate.
Is it possibe to add more than 1 bluetooth address in the cfg file?

Regards,
John

**Comment by sbf-** [comment]
Do they have the same NetID?
Did you set MIS_Enabled=1 in config file?

You can't set multiple BT addresses, however, you can use multiple config files. See [wiki](https://github.com/SBFspot/SBFspot/wiki/Installation-Linux-SQLite) section "Remarks" at the end
