### ISSUE TITLE
Can you tell me how exactly the sbfspot is working?

### ISSUE THREAD

**Issue by Rebo4n** [SBFspot/SBFspot#220]
I am looking forward to knowing how the SpFspot is working, which communication protocol it uses and everything that can help me to create something like it for other inverters.
Looking forward to your response.

**Comment by sbf-** [comment]
SBFspot uses SMAdata2+ which is a closed protocol of SMA.
I don't see how you should use it for other inverters

**Comment by Rebo4n** [comment]
First thank you for this information.
I just want to know the steps that you followed to code it. 
And how the SMAdata+ look like or anything that can help.
Thank you for your help

**Comment by sbf-** [comment]
Sorry, I have no info to share about this...
Try -d5 option for messages between host and inverter
