### ISSUE TITLE
How to run SBFspot every 20s??

### ISSUE THREAD

**Issue by Rebo4n** [SBFspot/SBFspot#221]

**Comment by Rebo4n** [comment]
thanks in advance

**Comment by sbf-** [comment]
Create a script to run SBFspot in an endless loop... but why should you do that?

**Comment by Rebo4n** [comment]
I did my own dashboard (webpage and android apk) and i want to see the changes of variable in real time from home from mysql database.

**Comment by webalexeu** [comment]
Hello,

Did you publish the webpage and apk?

I'm interested

Alex
________________________________
De : Rebo4n <notifications@github.com>
Envoyé : vendredi 25 mai 2018 14:14
À : SBFspot/SBFspot
Cc : Subscribed
Objet : Re: [SBFspot/SBFspot] How to run SBFspot every 20s?? (#221)


I did my own dashboard (webpage and android apk) and i want to see the changes of variable in real time from home from mysql database.
