### ISSUE TITLE
No free api anymore at wunderground

### ISSUE THREAD

**Issue by mark-joe** [SBFspot/SBFspot#222]
Dear SBFspot team,
Installed everything (including new Raspberry OS) well within an hour thanks to the excellent documentation (it was literately copy/paste) Well done! Keep up the good work.
 
Coming to the end of your documentation it mentioned adding temperature. Unfortunately wunderground does not provide that anymore. See:
https://www.wunderground.com/weather/api:
"To improve our services and enhance our relationship with our users, we will no longer provide free weather API keys as part of our program"
To improve our services???
Too bad. Maybe they add https://openweathermap.org/appid as an alternative, or implement it in an extra routine in SBFspot

**Comment by stripwax** [comment]
Did anyone pick this up?  I see the wiki reflects the current state of the world (i.e. wunderground no longer giving API keys and suggesting that openweathermap might be an alternative) but is anything in progress? If not I can maybe take a look.. looking to contribute back (I just found SBFSpot today)

**Comment by sbf-** [comment]
I'm currently working on a solution to read weatherdata from openweathermap.org and send temperature to pvoutput.

**Comment by henkpls** [comment]
Hi all,

My temperature data from wunderground ended last week, so I made a quick patch for the Raspberry to substitute the outside temperature for the inverter temperature in the SQlite database. As I live in the Netherlands I'm using a local weather API from http://weerlive.nl/delen.php, but it's easy to adapt for another provider by changing the url string.

I have no experience with C++, so I used this example code https://gist.github.com/connormanning/41efa6075515019e499c to get the temperature. I only modified the source file db_SQLite_Export.cpp and the makefile (to add the required libraries). See attached zip file.
I hope pvoutput will add some working weather API's soon, but in the meantime this may be of some help. As API key and location are hard-coded, you have to do the build yourself.
Please follow the WIKI (SBFspot V3 Quick Reference Linux EN 1.0), but if you have a working environment only install required stuff and build the SPFspot executable (sudo make install_sqlite)

[SMA.zip](https://github.com/SBFspot/SBFspot/files/2941757/SMA.zip)

**Comment by sbf-** [comment]
See [Wunderground Old API Decommissioning](https://forum.pvoutput.org/t/wunderground-old-api-decommissioning/1753)
