### ISSUE TITLE
SBFspot libboost_date_time.so.1.58.0

### ISSUE THREAD

**Issue by htttito** [SBFspot/SBFspot#223]
Hi support :-) !
I have installed ubuntu 18.04 and there is only  libboost_date_time.so.1.62 or 1.65 available.
Can you help me?
My error is: 
/usr/local/bin/sbfspot.3/SBFspot: error while loading shared libraries: libboost_date_time.so.1.58.0: cannot open shared object file: No such file or directory

Thank you!

**Comment by sbf-** [comment]
You will have to recompile sbfspot with the new libraries.
