### ISSUE TITLE
Unknown Inverter Type SBS3.7-10

### ISSUE THREAD

**Issue by gepa5943** [SBFspot/SBFspot#230]
Please could you update the configuration file the following inverter:
0x0000248C and Inverter Type=SBS3.7-10
as SMA Sunny Boy Storage 3.7

Here is the output file is receive:
---------------------------------
SBFspot V3.4.0
Yet another tool to read power production of SMA solar inverters
(c) 2012-2018, SBF (https://github.com/SBFspot/SBFspot)
Compiled for Linux (LE) 32 bit with SQLite support
Commandline Args: -v -finq -nocsv
Reading config '/usr/local/bin/sbfspot.3/SBFspot.cfg'
Mon Jul  9 20:12:59 2018: INFO: Starting...
sunrise: 05:44
sunset : 21:27
Connecting to Local Network...
Initializing...
SUSyID: 125 - SessionID: 924767905 (0x371ED6A1)
Inverter IP address: 192.168.1.20 from SBFspot.cfg
Logon OK
Unknown Inverter Type. Report this issue at https://github.com/SBFspot/SBFspot/issues with following info:
0x0000248C and Inverter Type=<Fill in the exact type> (e.g. SB1300TL-10)
SUSyID: 361 - SN: 3002897473
Device Name:      SBS3.7-10 473
Device Class:     DevClss7
Device Type:      UNKNOWN TYPE
Software Version: 01.00.73.R
Serial number:    3002897473
SUSyID: 361 - SN: 3002897473
Device Status:      Ok
SUSyID: 361 - SN: 3002897473
Device Temperature: 0.0°C
SUSyID: 361 - SN: 3002897473
Pac max phase 1: 3680W
Pac max phase 2: 0W
Pac max phase 3: 0W
SUSyID: 361 - SN: 3002897473
Energy Production:
	EToday: 0.000kWh
	ETotal: 63.362kWh
	Operation Time: 279.68h
	Feed-In Time  : 229.16h
SUSyID: 361 - SN: 3002897473
DC Spot Data:
	String 1 Pdc:   0.000kW - Udc:   0.00V - Idc:  0.000A
	String 2 Pdc:   0.000kW - Udc:   0.00V - Idc:  0.000A
SUSyID: 361 - SN: 3002897473
AC Spot Data:
	Phase 1 Pac :   0.284kW - Uac: 239.13V - Iac:  1.255A
	Phase 2 Pac :   0.000kW - Uac:   0.00V - Iac:  0.000A
	Phase 3 Pac :   0.000kW - Uac:   0.00V - Iac:  0.000A
	Total Pac   :   0.284kW
SUSyID: 361 - SN: 3002897473
Grid Freq. : 49.99Hz
********************
* ArchiveDayData() *
********************
startTime = 5B428960 -> 09/07/2018 00:00:00
**********************
* ArchiveMonthData() *
**********************
startTime = 5B38B430 -> 01/07/2018 13:00:00
Reading events: 2018-Jul-01
Mon Jul  9 20:13:00 2018: INFO: Done.

--------------------------------------------------

Thanks in advance,
Patrick

**Comment by sbf-** [comment]
Added to V3.5.0
