### ISSUE TITLE
Sunny Boy 1.5 without bluetooth to PVoutput

### ISSUE THREAD

**Issue by RamonNoya** [SBFspot/SBFspot#234]
Hi, I'm a new user and I need some help. I want to link my sunny portal with Pvoutput. Is there any dummies manual?? Thanks  a lot!

**Comment by sbf-** [comment]
There is no direct link between sunny portal and PVOutput.
You need to retrieve the data from your Sunny Boy with SBFspot and store it locally and SBFspotUploadDaemon will send it to PVOutput. See [wiki](https://github.com/SBFspot/SBFspot/wiki/Installation-Linux-SQLite) for more info how to do this on Raspberry Pi

**Comment by RamonNoya** [comment]
Thanks! I’ll try it!
