### ISSUE TITLE
Starting SBFspotUploadDaemon with systemd

### ISSUE THREAD

**Issue by svde** [SBFspot/SBFspot#237]
I'm trying to improve my SBFspot rpm package https://build.opensuse.org/package/show/home:stefan_van_der_eijk/SBFspot (for FC28). One of the things I want to achieve is to let SBFspotUploadDaemon run with its own user and use configuration files in /etc/SBFspot/. It seems that SBFspotUploadDaemon needs to read the configuration file from the same directory. Can that be changed?

**Comment by sbf-** [comment]
You can use -c as described [here](https://github.com/SBFspot/SBFspot/wiki/Installation-Linux-SQLite)

**Comment by svde** [comment]
Thanks!
