### ISSUE TITLE
manual issue - download of master branch instead of version

### ISSUE THREAD

**Issue by KanteTaete** [SBFspot/SBFspot#240]
Hello,

in the current installation manual, one step is downloading the current sourcecode via:
> wget –N https://github.com/SBFspot/SBFspot/archive/V3.4.0.tar.gz

... but the folder 
> https://github.com/SBFspot/SBFspot/archive/

doesn't exist and so, the current version can't be downloaded.

Wasn't it better here to give a link to the current (master) branch (zip file or directory) of SBFspot?
e.g. 
> wget -N https://github.com/SBFspot/SBFspot/archive/master.zip

Of course, then the next steps in the manual need to be updated as well.

Btw: Is there another possibility to integrate the sources into apt, etc. to be able to upgrade the SBFspot version with tools like apt, etc?

Regards!

**Comment by sbf-** [comment]
`https://github.com/SBFspot/SBFspot/archive/` exists but you can't access it as such...
Master branch is not a stable release, but indeed, the way it's documented now needs a modification with every stable release.
In the past I have had several proposals to help me with `apt` repositories, but it never got completed.
I'm now working on [sbfspot-config](https://github.com/SBFspot/sbfspot-config), a semi-automated installation/configuration tool - but that will be only for Raspberry Pi
