### ISSUE TITLE
MySQL broken?

### ISSUE THREAD

**Issue by LaCruz75** [SBFspot/SBFspot#247]
I just build a 3.50-version with "make mysql" on Ubuntu 18.04/18.10. MySQL Server/Client and Libs are installed.

On startup of the binary I got this:
```
SBFspot V3.5.0
Yet another tool to read power production of SMA solar inverters
(c) 2012-2018, SBF (https://github.com/SBFspot/SBFspot)
Compiled for Linux (LE) 64 bit
Warning: Ignoring keyword 'SQL_Hostname'
Warning: Ignoring keyword 'SQL_Username'
Warning: Ignoring keyword 'SQL_Password'
```
No new data will be stored in database. So also UploadDaemon has no work.

On building a V3.4.1 it was quiet okay:
```
SBFspot V3.4.1
Yet another tool to read power production of SMA solar inverters
(c) 2012-2018, SBF (https://github.com/SBFspot/SBFspot)
Compiled for Linux (LE) 64 bit with MySQL support
```

Preprocessor flag -D is shown on output:
`g++ SBFspot.cpp -c -Wall -O2 -Wno-unused-local-typedefs -I -DUSE_MYSQL -o mysql/obj/SBFspot.o`

If I add -DUSE_MYSQL also on Flags in makefile:
`CFLAGS     := -c -Wall -O2 -Wno-unused-local-typedefs -I -DUSE_MYSQL`

Then preprocessor flag -D is shown double on output:
`g++ SBFspot.cpp -c -Wall -O2 -Wno-unused-local-typedefs -I -DUSE_MYSQL -DUSE_MYSQL -o mysql/obj/SBFspot.o`

but on start compiled binary:

```
SBFspot V3.5.0
Yet another tool to read power production of SMA solar inverters
(c) 2012-2018, SBF (https://github.com/SBFspot/SBFspot)
Compiled for Linux (LE) 64 bit with MySQL support
...
Libraries used:
        MySQL V5.7.22 (Client)
        BOOST V1.67.0
```

Strange?!

**Comment by sbf-** [comment]
Strange indeed. I ll have to check this.
