### ISSUE TITLE
make does not work on my Raspberry Pi

### ISSUE THREAD

**Issue by wil76** [SBFspot/SBFspot#249]
I'm trying to setup SBFspot on my raspberry Pi 2.
but nothing happens after this:

![image](https://user-images.githubusercontent.com/24221828/46016315-c37aba00-c0d4-11e8-9cb7-598c63128335.png)

what can I do ?

**Comment by PjotrekSE** [comment]
What happens? Does it just hang there? 
What operating system? 
Can you open other terminals to the RasPi, or does the entire RasPi hang?
-When I compiled on older RasPis, sometimes it took a long time compiling some of the sources, including ArchData. Now  I always compile on a new RasPi 3 B+, it is *much* quicker.

**Comment by wil76** [comment]
I'm not confirm with compiler on Raspberry.
but obviously "makefile" starts all compiles in parallel. 
this of course does stress a little raspberry strongly.
is there an option to serialize the compile steps.

**Comment by sbf-** [comment]
AFAIK there is no parallel compilation...
Anyway, today I released [sbfspot-config](https://github.com/SBFspot/sbfspot-config)
It comes with precompiled binaries for Raspberry Pi running stretch. No need to install development tools and libraries, just run this command and give it a try:
`curl -s https://raw.githubusercontent.com/sbfspot/sbfspot-config/master/sbfspot-config | sudo bash`

**Comment by wil76** [comment]
Greta job, this will make the setup much easier.

my environment is running now.
but I had to compile the objects one after each other.

**Comment by wil76** [comment]
It obviously hangs. I have to cancel the putty session. But than the Raspi is still running. I‘m compiling on a Raspi pi 2. I‘m using a Pi 3 B+ for production and don’t want to install tens of packages only for compiling SBFspot.Is it possible to get a compiled version. I‘m fighting since month with a python module to read the inverter data via Bluetooth. But this does not support more than one SMA component. Are there other compile options to further evaluate. I already tried -v. But I‘m not able to investigate the problem
		
		

		Outlook für iOS beziehen
	




On Tue, Sep 25, 2018 at 9:27 PM +0200, "Peter Kling" <notifications@github.com> wrote:












What happens? Does it just hang there?

What operating system?

Can you open other terminals to the RasPi, or does the entire RasPi hang?

-When I compiled on older RasPis, sometimes it took a long time compiling some of the sources, including ArchData. Now  I always compile on a new RasPi 3 B+, it is much quicker.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.







What happens? Does it just hang there? 
What operating system? 
Can you open other terminals to the RasPi, or does the entire RasPi hang?
-When I compiled on older RasPis, sometimes it took a long time compiling some of the sources, including ArchData. Now  I always compile on a new RasPi 3 B+, it is *much* quicker.

**Comment by sbf-** [comment]
See my comment above about sbfspot-config
