### ISSUE TITLE
SBFspot "CRITICAL Login failed"

### ISSUE THREAD

**Issue by BasVal1978** [SBFspot/SBFspot#254]
Trying to log my Sunny Boy inverter via SBFspot on a Raspberry Pi but i keep getting a Critical Error

When i use my laptop with build in bluetooth and the Sunny Explorer software user password 0000 and 1111 are accepted so the passwords are correct. 

Could this be a bluetooth setting or a problem with my Raspberry Pi?

**Comment by sbf-** [comment]
Unless you have a Raspberry Pi 3 or Zero W with built-in Bluetooth, the best hint I can give is to use a dongle of another brand.

**Comment by BasVal1978** [comment]
Hi, i allready tried 2 different Bluetooth donlges on my (old) Pi2. 
Next step would be to try with a Pi3.
I found something online for SMA bluetooth settings but the file is offline. Maybe SMA requires specific bluetooth parameters?

**Comment by Dylantje** [comment]
I do also have a problem with the BT login.. Cannot connect?
And i do have the good bt adres..

**Comment by sbf-** [comment]
Still not working?
Please post a log file (-d5 -v5)
