### ISSUE TITLE
Volkszähler Script

### ISSUE THREAD

**Issue by WolfgangFahl** [SBFspot/SBFspot#258]
In 2014 i had posted a script to the Volkzähler Wiki
https://wiki.volkszaehler.org/hardware/channels/solar_inverters/sma?redirect=1

that reads SMASpot data and uploads it to the Volkszähler solution. I now have updated SMASpot to the lastest SBFSpot version and would like to update the script. I also think it might be worthwhile to host the script together with SBFspot in a contrib area. What do you think ?

**Comment by sbf-** [comment]
Sure, no problem!
What do you suggest? Via pull request or...? Don't know exactly what's possible here.
