### ISSUE TITLE
Installer fails on Raspberry Zero W

### ISSUE THREAD

**Issue by DocSnyd3r** [SBFspot/SBFspot#260]
Hi,

the installer fails with the following output i use (Linux sunpi 4.9.24+ #993 Wed Apr 26 17:56:54 BST 2017 armv6l GNU/Linux). Will try manual install later.

SBFspot Configuration Tool V1.0.11
Running on Raspberry Pi Zero W Rev 1.1
Checking whiptail... Installed.
architecture=armhf
Raspbian GNU/Linux 8.0 (jessie)
username=pi
userhome=/home/pi
Minimum SBFspot version supported by this tool is 3.5.0
Request to install latest version (3.5.0)
Searching for existing configuration(s)...
Reading defaults from /var/tmp/sbfspot.3/sbfspot.defaults... Done
Saving defaults to /var/tmp/sbfspot.3/sbfspot.defaults... Done
Performing some checks before installation... Done
Downloading https://github.com/sbfspot/sbfspot/releases/download/V3.5.0/sbfspot-sqlite-arm-linux.tar.gz
Copying files...
SBFspot.db exists
Checking database...
Schema Version=1
Configuring SBFspot... Done
Running SBFspot...
/usr/local/bin/sbfspot.3/SBFspot: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/bin/sbfspot.3/SBFspot)
/usr/local/bin/sbfspot.3/SBFspot: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/local/bin/sbfspot.3/SBFspot)

Installation aborted

PS manual installation worked fine

**Comment by sbf-** [comment]
Script has not been tested with jessie, so it seems it is not compatible...
See https://github.com/SBFspot/sbfspot-config/issues/1
