### ISSUE TITLE
Unknown Inverter Type  STP4.0-3AV-40 016

### ISSUE THREAD

**Issue by jivonl** [SBFspot/SBFspot#261]
0x00002480 and Inverter Type= STP4.0-3AV-40 016
Apparaattype, SUNNY TRIPOWER 4.0

SBFspot V3.5.0
Yet another tool to read power production of SMA solar inverters
(c) 2012-2018, SBF (https://github.com/SBFspot/SBFspot)
Compiled for Windows (LE) 32 bit with SQLite support
Commandline Args:
Inverter IP address: 10.35.0.54 from SBFspot.cfg
Unknown Inverter Type. Report this issue at https://github.com/SBFspot/SBFspot/issues with following info:
0x00002480 and Inverter Type=<Fill in the exact type> (e.g. SB1300TL-10)

**Comment by sbf-** [comment]
You can find the updated taglist files [here](https://github.com/SBFspot/SBFspot/tree/master/SBFspot)
