### ISSUE TITLE
multiple speedwire connection different passwords

### ISSUE THREAD

**Issue by SBFfan** [SBFspot/SBFspot#262]
I have two inverter per speedwire connected with different passwords. The password of the first inverter I can not change and is default to 0000. The other password I can set myself but not on 0000 or 1111. Individually I can read the inverter, unfortunately I can not read both together. My problem is the different passwords. Is there a solution here or maybe I have read something over. 

```
#SBFspot.cgf
# User password (default 0000)
# SB 5000TL-21 285, SB4.0-1AV-40 635
IP_Address = 192.168.2.46,192.168.2.40
Password = start123,0000
```

**Comment by sbf-** [comment]
Create 2 config files, 1 for each inverter with IP address and password.
SBFspot.db database is the same for the 2 inverters
Start SBFspot with each config file
`SBFspot -cfgSB5000.cfg`
`SBFspot -cfgSB40.cfg`
