### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by rucksman** [SBFspot/SBFspot#265]
Because of the problems described in issue #264 I wanted to install SBFspot on a different machine. But after
`make mysql`
I get this error after some time:
```
g++ SBFspot.cpp -c -Wall -O2 -Wno-unused-local-typedefs -DUSE_MYSQL -o mysql/obj/SBFspot.o
In file included from SQLselect.h:46:0,
                 from SBFspot.cpp:72:
db_MySQL.h:41:25: fatal error: mysql/mysql.h: Datei oder Verzeichnis nicht gefunden
 #include <mysql/mysql.h>
                         ^
compilation terminated.
make: *** [mysql/obj/SBFspot.o] Fehler 1
```

Any idea what goes wrong here?

Just for your information: The old machine was a raspberry pi 3, the new one is a small server running ubuntu server 16.04 LTS.

**Comment by freekdk** [comment]
You should install a packet like mysql-devel.

**Comment by rucksman** [comment]
You are right... for some reason libmysqld-dev was missing... Thanks!
