### ISSUE TITLE
No more data since 21/1 at 14.15

### ISSUE THREAD

**Issue by broke23** [SBFspot/SBFspot#270]
I have no more data being uploaded to pvoutput.org.

I retrieved the data manually (9 days) yesterday but daemon is not uploading yesterday. Nor today. Nor when I start it manually. 

Data is in db for today though ... (vwdaydata)

Any thoughts what to check exactly? Logs not showing anything apart from daemon starting

This is my parent's system. Mine is still working flawlessly on same Pvoutput account... So that's not the issue...

**Comment by sbf-** [comment]
What are the last records of vwPvoData. That's the view used for the upload.

**Comment by broke23** [comment]
From what I can see. On Android it's crashing my db and deleting it apparently. On windows when I want to see contents it's showing stuff from previous view all the time...

Thinking it's corrupt?

**Comment by sbf-** [comment]
Run a check to see if it's corrupt:
`pragma integrity_check;`

**Comment by sbf-** [comment]
You are integrity checking an empty (in-memory) database...

Correct syntax is: `sqlite3 <path_to_database>`
```
pi@raspberrypi:~ $ sqlite3 /home/pi/smadata/SBFspot.db 
SQLite version 3.8.7.1 2014-10-29 13:59:56
Enter ".help" for usage hints.
sqlite> pragma integrity_check;
ok
sqlite> .quit
```

**Comment by broke23** [comment]
sqlite> pragma integrity_check;
*** in database main ***
Page 8785: btreeInitPage() returns error code 11
On tree page 8846 cell 2: Child page depth differs
Page 8787: btreeInitPage() returns error code 11
Page 8788: btreeInitPage() returns error code 11
On tree page 8846 cell 5: Child page depth differs
Page 8786: btreeInitPage() returns error code 11
On tree page 8846 cell 9: Child page depth differs
On tree page 8846 cell 10: Child page depth differs
Error: database disk image is malformed

**Comment by sbf-** [comment]
So it's pretty clear: db is corrupt
You can try [this option](https://stackoverflow.com/questions/18259692/how-to-recover-a-corrupt-sqlite3-database) to recover some of the data.

**Comment by broke23** [comment]
```
1 sqlite3 dbWithCorruptTable.sqlite (Obviously replace "dbWithCorruptTable" to your sqlite3 file that has the corrupt table)
2 .mode insert
3 .output dump_all.sql
4 .dump
5 .exit
6 Manually edit the dump_all.sql file in a text editor and remove the transaction statements. Usually there is a "BEGIN TRANSACTION" statement on the 2nd line of the file and a "ROLLBACK" statement on the last line. Remove these and save the file
```
DB size went from 50 mb to 65 in sql format. Changing back from sql to db it ended up being 18mb?

**It is working again though!**

**Comment by broke23** [comment]
`1 sqlite3 dbWithCorruptTable.sqlite (Obviously replace "dbWithCorruptTable" to your sqlite3 file that has the corrupt table)
2 .mode insert
3 .output dump_all.sql
4 .dump
5 .exit
6 Manually edit the dump_all.sql file in a text editor and remove the transaction statements. Usually there is a "BEGIN TRANSACTION" statement on the 2nd line of the file and a "ROLLBACK" statement on the last line. Remove these and save the file`

Seems to be working. 50 mb > 65 in sql, back to db =18 mb? 

Uploads are coming though I'm lacking partial data?

**Comment by broke23** [comment]
All seems fine again! Thanks SBF
