### ISSUE TITLE
mysql no Power=0 and TimeStamp

### ISSUE THREAD

**Issue by htttito** [SBFspot/SBFspot#273]
Hi again!
There is no Power=0 in vwDaydata or somewhere?
The Table stop a little bit before Power=0 .
There is also no Timestamp like in .csv for Power=0
(It is all after sunset)

Thanks!

**Comment by htttito** [comment]
The Timestamp in DayData for example "1550334300" what does it stand for?

**Comment by sbf-** [comment]
It's a UNIX timestamp (https://www.unixtimestamp.com/index.php)
What do you mean with

> There is no Power=0 in vwDaydata or somewhere?

**Comment by htttito** [comment]
Hi thanks!
I mean that SbfSpot dont write zero values in the mysql Table!

**Comment by htttito** [comment]
You can see that there is missing Timestamp and Power in all tables, after sunrise.
Look at https://pv.tito.dynu.net/ at the end of the site...

**Comment by sbf-** [comment]
yes, that's by design. To save space in the db

**Comment by htttito** [comment]
Thanks!
Is there a possibility to change this for mysql?
In csv there are zero values....

**Comment by sbf-** [comment]
The zero's in csv is to be compatible with SMA's SunnyExplorer
Have a look at db_MySQL_Export.cpp
In the db_SQL_Export::day_data() function I'm looking for start and end of production.
Comment out these sections and define first_rec, last_rec

**Comment by htttito** [comment]
OhOh my php.....
The code to find first and last_rec  is very good.
I only need one entry after sunset with Power=0 for my website.
It is not so important, its only to show it right ;-) 
If you have time...can you help me with the code?
Thanks :-)!

**Comment by sbf-** [comment]
Try this (didn't test it)
Change
``` C
// Store data from first to last record
for (unsigned int idx = first_rec; idx <= last_rec; idx++)
```
To
``` C
// Store data from first to last record+1
for (unsigned int idx = first_rec; idx <= last_rec+1; idx++)
```
This should add 1 record with timestamp and 0 Watts

**Comment by htttito** [comment]
It look good, i will see it exactly tomorrow!
VERY VERY COOL!
Thanks :-)
