### ISSUE TITLE
SB1.5-1VL-40 temperature readout 0 but temperture is available on modbus

### ISSUE THREAD

**Issue by DarkShadowNight** [SBFspot/SBFspot#282]
Hello,

I noticed the temperature readout of my SB1.5-1VL-40 is 0 with speedwire connection.
I have modbus enabled, and it is possible to readout temperature at register 40219 and 40222.
You need installer password to enable modbus so I won't recommend to implement modbus.
Can you use these registers to readout temperature? Any possibilities over speedwire do you think?

**PS:** Some strange modbus things, reading DC power is not available, in "power table", but is in "mppt tabe"...

https://www.sma.de/fileadmin/content/landingpages/pl/FAQ/SunSpec_Modbus-TI-en-15.pdf
Page 22

Thanks, keep up the good work!

**Comment by sbf-** [comment]
Well, I suppose internal temperature is not available in SMAdata2+ protocol. I'm afraid there is nothing to fix here. SBFspot can't read modbus registers.
