### ISSUE TITLE
Time of cronjob to retrieve monthly data

### ISSUE THREAD

**Issue by H4ndl3** [SBFspot/SBFspot#284]
In the wiki the cron job to retrieve monthly data is configured to run daily at 05:55 in the morning ([link](https://github.com/SBFspot/SBFspot/wiki/Installation-Linux-SQLite#%EF%B8%8F-automation)). However, during winter the inverter won't be up at this time in my area because it is still dark then. Why was 05:55 being chosen?

**Comment by HarvsG** [comment]
It used the `-finq` option which wakes the inverter even if there is no sunlight

**Comment by H4ndl3** [comment]
@sbf- just to be sure: Will there be a problem if the `monthdata` cronjob runs at the same time as a `daydata` cronjob?

**Comment by sbf-** [comment]
No problem, but it's overkill to run it every 5min as only 1 record will be added per day.
