### ISSUE TITLE
Unknown Inverter Type: STP5.0-3AV-40

### ISSUE THREAD

**Issue by jschonen** [SBFspot/SBFspot#287]
Sunny Tripower 5.0

Unknown Inverter Type. Report this issue at https://github.com/SBFspot/SBFspot/issues with following info:
0x00002481 and Inverter Type=<Fill in the exact type> (e.g. SB1300TL-10)
SUSyID: 378 - SN: xxxxxxxxxx
Device Name:      STP5.0-3AV-40 173
Device Class:     Solar Inverters
Device Type:      UNKNOWN TYPE

**Comment by fonske** [comment]
Try to add:
9345=STP5.0-3AV-40\0\Sunny Tripower 5.0
to the text files in your language
TagListEN-US.txt 
TagListNL-NL.txt`
in /usr/local/bin/sbfspot.3 (on Linux computer)

**Comment by sbf-** [comment]
Get latest Taglist*.txt files [here](https://github.com/SBFspot/SBFspot/tree/master/SBFspot)
