### ISSUE TITLE
Is there still Windows support?

### ISSUE THREAD

**Issue by KiavashS** [SBFspot/SBFspot#298]
Hi there, does this still support Windows installations? I can't see a windows version of the latest release.

**Comment by sbf-** [comment]
Sure, I'll add them asap

**Comment by KiavashS** [comment]
Thanks, I was hesitant to ask as I thought I must be missing something obvious :)

**Comment by sbf-** [comment]
Windows executables added to latest release (V3.5.2)

**Comment by KiavashS** [comment]
Great. Got it and have it working. Thankyou.
