### ISSUE TITLE
SMA SPR-4600M-DE not recognized

### ISSUE THREAD

**Issue by MadMe86** [SBFspot/SBFspot#299]
Hello!
I'm trying to connect my fathers PV-Installation to iobroker. But i don't get SBFspot running...

The Installation is the following(Plant set up by Sunpower):
The Inverter: SPR-4600M-A
is connected to a datenlogger: spr-pmr-dlog
this one is connected by radio with a gateway: spr-pmr-gtwy
The Gateway is sending the Data directly to Sunpower. I could sniff the data on my FritzBox and they make sense.
The script sbfspot-config says "ERROR: Connection to inverter failed!"
Is the Hardware not supporteted? what am i doing wrong?

Thanks in advance!

**Comment by sbf-** [comment]
SBFspot should connect directly to the inverter via its IP

> I could sniff the data on my FritzBox and they make sense.

What do you see exactly? SBFspot expects SMAData2+ which shouldn't make sense

I'm afraid this will never work if you can't connect via IP-Address. Does it work with Sunny Explorer?
