### ISSUE TITLE
SBFspot upload daemon libcurl compatibility

### ISSUE THREAD

**Issue by Hindosh** [SBFspot/SBFspot#307]
Running on the lateste raspian Buster image. the SBFspotUpload daemon is not compatble anymore
Libcurl3 packages cannot be installed anymore in Buster

jul 14 13:48:14 raspberrypidomo systemd[1]: Started SBFspot Upload Daemon.
jul 14 13:48:14 raspberrypidomo SBFspotUploadDaemon[25224]: /usr/local/bin/sbfspot.3/SBFspotUploadDaemon: /usr/lib/arm-linux-gnueabihf/libcurl.so.4: version `CURL_OPENSSL_3' not found
jul 14 13:48:14 raspberrypidomo systemd[1]: SBFspotUpload.service: Main process exited, code=exited, status=1/FAILURE
jul 14 13:48:14 raspberrypidomo systemd[1]: SBFspotUpload.service: Failed with result 'exit-code'.

**Comment by TerrorSource** [comment]
did you try removing libcurl3, installing libcurl4 and re-compile via the manuall install guide?

**Comment by Hindosh** [comment]
no used the config installer 
curl -s https://raw.githubusercontent.com/sbfspot/sbfspot-config/master/sbfspot-config | sudo bash

**Comment by TerrorSource** [comment]
@Hindosh try the manual guide. it worked for me with the manual guide on a Pi 4 4gb.

**Comment by sbf-** [comment]
There is a temporary workaround described [here](https://github.com/SBFspot/SBFspot/issues/295)

**Comment by Hindosh** [comment]
"You can find it here: https://github.com/SBFspot/SBFspot/releases/edit/V3.5.2"
seems inaccessible via the browser (404 error)
can you send a directlink to: Download SBFspotUploadDaemon_buster 
thnx
