### ISSUE TITLE
Merge db file

### ISSUE THREAD

**Issue by TerrorSource** [SBFspot/SBFspot#308]
Hi,

I moved to a new Pi with SBFSpot.
Copied all the csv files (2014-2019) to the new pi but im stuck with the SVFspot.db file.
Old one: 22.527 kb
New one: 904kb

Already run
/usr/local/bin/sbfspot.3/SBFspot -ad300
/usr/local/bin/sbfspot.3/SBFspot -am60
/usr/local/bin/sbfspot.3/SBFspot -ae7

But looks like old data from 300d and older is not picked up and put into the db file.
How can i merge them by hand?

Couldnt find a how-to online.

**Comment by sbf-** [comment]
Most inverters only keep 62 days of daydata. The -ad300 is the limit if for some inverters this should be possible.
Just copy the old db to the new pi... simple as that.

**Comment by TerrorSource** [comment]
@sbf- Thanks.

Uploaded the db file to the new pi and re-run all 3 command's.
DB file grew from 22.527kb to 22.601kb
