### ISSUE TITLE
Unknown Inverter Type

### ISSUE THREAD

**Issue by userjp123** [SBFspot/SBFspot#309]
0x00002483 and Inverter Type=SMA STP 8.0-3AV-40

**Comment by sbf-** [comment]
Thanks,
I'll add it asap

**Comment by userjp123** [comment]
Thank you !
What have I to do to implement this change ?
I have changed the file <TagListDE-DE.txt>. (what is the function of this file?)
Do I have to change the database-entry in the table <inverters> ?
I am running Version 3.5.1 of SBFspot.
Thank you again !

**Comment by sbf-** [comment]
If you changed or downloaded the taglist files (or only the one for your language) you don't need to do anything else.
