### ISSUE TITLE
Warning from systemctl status SBFUploadDaemon

### ISSUE THREAD

**Issue by freekdk** [SBFspot/SBFspot#314]
When performing the command in the title, the following warning is shown:
/etc/systemd/system/SBFspotUpload.service:10: Failed to parse service restart specifier, ignoring: on-succes
This file has been created using the example on the Wiki.

**Comment by sbf-** [comment]
On Raspberry Pi? Raspbian Version?

**Comment by freekdk** [comment]
Yes on Raspberry Pi 2B, but on openSUSE Tumbleweed.

**Comment by scotte** [comment]
Just to be sure - double check that you don't have a typo - is last "s" in "success" missing? From the error message pasted above, that might be the case. The full line should look like:

```
Restart=on-success
```

**Comment by sbf-** [comment]
> Failed to parse service restart specifier, ignoring: on-succes

Is that a typo?
It should be `Restart=on-success` with double 's'

**Comment by freekdk** [comment]
Indeed, the double 's' was a single one. Now all is OK.

**Comment by freekdk** [comment]
Forgot to say: Many thanks.

**Comment by sbf-** [comment]
Geen probleem... soms zit het in details ;-)
