### ISSUE TITLE
Error upload daemon after update to Debian Buster

### ISSUE THREAD

**Issue by Itsmmai** [SBFspot/SBFspot#317]
Hi,

After the update to Debian 10 buster I get an error when running SBFspotUploadDaemon

./SBFspotUploadDaemon: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./SBFspotUploadDaemon)

Help ?? Please :-)

Kind regards,
Abel

**Comment by sbf-** [comment]
See #295 voor workaround

**Comment by Itsmmai** [comment]
To bad. this isn't working for me :-(

<img width="840" alt="Schermafbeelding 2019-08-10 om 20 16 43" src="https://user-images.githubusercontent.com/24639986/62825438-e8243700-bbab-11e9-8402-4e2f28654872.png">

**Comment by sbf-** [comment]
Running on raspberry pi?

**Comment by Itsmmai** [comment]
No, nuc (Intel)

________________________________
Van: SBF <notifications@github.com>
Verzonden: Sunday, August 11, 2019 12:47:41 AM
Aan: SBFspot/SBFspot <SBFspot@noreply.github.com>
CC: Ab Helversteijn-Smit <ab@helversteijn-smit.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [SBFspot/SBFspot] Error upload daemon after update to Debian Buster (#317)


Running on raspberry pi?

**Comment by sbf-** [comment]
I see. In that case you will have to recompile the daemon.
