### ISSUE TITLE
unknown inverter: Sunny Boy Storage 5.0 (SBS5.0-10) & SUNNY TRIPOWER 10.0 (STP10.0-3AV-40)

### ISSUE THREAD

**Issue by joanwa** [SBFspot/SBFspot#327]
got two more unknowns: one PV and one Battery inverter

0x00002484: Inverter Type=SUNNY TRIPOWER 10.0 (STP10.0-3AV-40)
0x0000248E: Inverter Type=Sunny Boy Storage 5.0 (SBS5.0-10)

**Comment by joanwa** [comment]
Also, for the devices, the temperature is not read:
Device Temperature: 0.0°C
Not sure if this temperature sensors are supported for all devices and are supposed to work

**Comment by sbf-** [comment]
Thanks, i'll add them asap.
Not every inverter reports its temperature via smadata2+ protocol. Maybe via  modus?

**Comment by zaziki23** [comment]
exactly the same issue for me.

is there any svn or development branch which i can check out in order to get a fix?
