### ISSUE TITLE
From Sqlite3 to MySQL

### ISSUE THREAD

**Issue by userjp123** [SBFspot/SBFspot#330]
MySQL:
An INT will always be 4 bytes no matter what length is specified.
int(8) ist not an integer with 8 bytes
-> CreateMySQLDB.sql has to be changed

I have made the following changes:
1.
	my S/N: 3xxxxxxxxx -> more than 4-byte-int
	Serial: int changed to BIGINT

2.	
changed all int(8) to bigint:
	ALTER TABLE Inverters MODIFY EToday BIGINT;
	ALTER TABLE Inverters MODIFY ETotal BIGINT;
	ALTER TABLE SpotData MODIFY EToday BIGINT;
	ALTER TABLE SpotData MODIFY ETotal BIGINT;
	ALTER TABLE DayData MODIFY TotalYield BIGINT;
	ALTER TABLE DayData MODIFY Power BIGINT;
	ALTER TABLE MonthData MODIFY TotalYield BIGINT;
	ALTER TABLE MonthData MODIFY DayYield BIGINT;

3.	
	events with more than 32 chars:
	one event: NewValue: (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna 
	OldValue varchar(32), -> 64
	NewValue varchar(32), -> 64

**Comment by sbf-** [comment]
Correct, INT(8) is used for display width (meaning is different compared to SQLite)
However, the MySQL documentation reveals this:

> All integer types can have an optional (nonstandard) attribute UNSIGNED. Unsigned values can be used when you want to allow only nonnegative numbers in a column and you need a larger upper numeric range for the column. For example, if an INT column is UNSIGNED, the size of the column's range is the same but its endpoints shift from -2147483648 and 2147483647 up to 0 and 4294967295.

So, Serial Number should be INT UNSIGNED, not BIGINT. This will save you a lot of storage.
