### ISSUE TITLE
PVOutput not working :  version `CURL_OPENSSL_3' not found

### ISSUE THREAD

**Issue by jvanbouchaute** [SBFspot/SBFspot#331]
Hi,
did a clean install on raspberry pi zero W - raspbian OS
using the installer tool. It installed SBFspot 3.5.2
The upload deamon fails to start however because of following error : 

/usr/lib/arm-linux-gnueabihf/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/local/bin/sbfspot.3/SBFspotUploadDaemon)

Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Comment by sbf-** [comment]
I still have to update this...
See #295 for a temporary workaround

**Comment by mhaket** [comment]
I have the same issues still on 3.6 release on a raspberry pi zero W
