### ISSUE TITLE
Unknown Inverter Type - One more new submission

### ISSUE THREAD

**Issue by onrust** [SBFspot/SBFspot#338]
0x00002483
Inverter Type=SMA Sunny Tripower STP 8.0-3AV-40

Thank you!

**Comment by onrust** [comment]
Apologies, I see this is fixed in a more recent version. I was still on 3.5.0 as per the instructions. Maybe it's good to update those to 3.6.0. https://github.com/SBFspot/SBFspot/wiki/Installation-Linux-SQLite

**Comment by sbf-** [comment]
It was not the intension to update the installation manual with every release, but to be clearer I added a link to the releases to remind the user he should have a look first.
Thanks for the remark.
