### ISSUE TITLE
MQTT_ is not show data inverter

### ISSUE THREAD

**Issue by rednumber686868** [SBFspot/SBFspot#346]
Hi,
Please help me pass this error:
My sbfspot.cfg enclose:
![sbfspot cfg](https://user-images.githubusercontent.com/50037759/71228727-93d95280-2315-11ea-8519-3ed001cd6d52.PNG)
I add _1 behide inverter serial like "serial_1" in MQTT
![thong so bien tan](https://user-images.githubusercontent.com/50037759/71228789-d733c100-2315-11ea-9eb6-1b38a0bae270.PNG)
And i run sbfspot like below:
![SBFspot install](https://user-images.githubusercontent.com/50037759/71228902-46a9b080-2316-11ea-84d9-cf3b4b445473.PNG)

Some condition, i can't edit serial in MQTT; and so please help me edit inverter serial or any way for showing on website
![du lieu bien tan](https://user-images.githubusercontent.com/50037759/71229245-62618680-2317-11ea-8c54-5e267337e98f.PNG)

Thanks all

**Comment by sbf-** [comment]
Sorry, but I don't understand what you're doing...
In your config you have several items not recognized by SBFspot:
`MQTT_ClientID`
`MQTT_Broker`
See [MQTT wiki](https://github.com/SBFspot/SBFspot/wiki/MQTT) for more info
