### ISSUE TITLE
Upload missing data to PVOutput, how does it know?

### ISSUE THREAD

**Issue by ir-fuel** [SBFspot/SBFspot#348]
It seems my Raspberry Pi lost connection to the internet. A power cycle resolved it, but I am missing about a month of data in PVOutput. The data is on my Raspberry Pi as I see the CSV for each day with the right values.

How does the upload daemon know which ones should be uploaded and which ones are already there? I did a donation to PVOutput so I should be able to go 90 days back. Most tickets talking about this are about downloading the missing data from the inverter, but that's not the issue in my case.

Thanks

![Screenshot 2019-12-21 at 14 52 20](https://user-images.githubusercontent.com/1573715/71308840-8e593680-2401-11ea-97eb-3c05c32217f5.jpg)

**Comment by sbf-** [comment]
If there is data in the database (SBFspot.db) the daemon should upload it automatically.
It looks at the pvoutput flag in the daydata table.
Execute this query in sqlite3 to see if there is data available:
`select * from pvodata limit 10;`
