### ISSUE TITLE
Add automate instructions to MQTT wiki page

### ISSUE THREAD

**Issue by VBP8501** [SBFspot/SBFspot#358]
Hello,

First of all, thank you very much for your time to develop this very handy software! I've put it to good use on a rapi for my new solar plant installation.

I use an MQTT to communicate between sensors and openhab. I was very pleased to learn that you also support this upload option. I would like to suggest an addition to this wiki page:
https://github.com/SBFspot/SBFspot/wiki/MQTT

I followed the instructions but while the command "./SBFspot -v5 -mqtt" worked perfectly, I noticed that the automated execution did not include the MQTT messages while uploading to pvoutput worked. In my case the issue was that the daydata and monthdata files in /usr/local/bin/sbfspot.3 did not contain the -mqtt keyword. I've added it and, while untested yet, think that will fix the problem. 

Could you add this instruction to avoid future user questions? Or else explain to me what I did wrong :)

Thanks

**Comment by sbf-** [comment]
Thanks, I added it to the wiki
