### ISSUE TITLE
SBFspotUploadDaemon CURL_OPENSSL_3 not found

### ISSUE THREAD

**Issue by deagel** [SBFspot/SBFspot#363]
Hi,
i installed yesterday with sbfspot-config. Today i checked my uploads but there are no uploads.

hi have more or less a min. install with NOOBS_v3_3_0.

pi@raspberrypi-4:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

root@raspberrypi-4:/var/log# systemctl status SBFspotUpload.service
* SBFspotUpload.service - SBFspot Upload Daemon
   Loaded: loaded (/usr/local/bin/sbfspot.3/SBFspotUpload.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-02-16 10:34:45 CET; 4min 0s ago
  Process: 13609 ExecStart=/usr/local/bin/sbfspot.3/SBFspotUploadDaemon (code=exited, status=1/FAILURE)
 Main PID: 13609 (code=exited, status=1/FAILURE)

Feb 16 10:34:45 raspberrypi-4 systemd[1]: Started SBFspot Upload Daemon.
Feb 16 10:34:45 raspberrypi-4 SBFspotUploadDaemon[13609]: /usr/local/bin/sbfspot.3/SBFspotUploadDaemon: /usr/lib/arm-linux-gnueabihf/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/local/bin
Feb 16 10:34:45 raspberrypi-4 systemd[1]: SBFspotUpload.service: Main process exited, code=exited, status=1/FAILURE
Feb 16 10:34:45 raspberrypi-4 systemd[1]: SBFspotUpload.service: Failed with result 'exit-code'.

**Comment by saylinglow** [comment]
This looks to me like closed issue #295 (and #331) https://github.com/SBFspot/SBFspot/issues/295https://github.com/SBFspot/SBFspot/issues/295
Sayling

**Comment by deagel** [comment]
Hi, yes look like #295 and #331 .
nice to have the workaround in a final solution that the bfspot-config handel it. ;)
