### ISSUE TITLE
No longer uploading to PVoutput

### ISSUE THREAD

**Issue by TorpedoBE** [SBFspot/SBFspot#365]
Hi All,

Suddenly my SBFspot stopped uploading to PVoutput.org.

In the syslog I see below issue, any idea what's wrong?

SBFspotUploadDaemon: Unable to open output file /tmp/SBFspotUploadDaemon.out: Success

regards,

Bart

**Comment by sbf-** [comment]
Reboot maybe?

**Comment by TorpedoBE** [comment]
been there, done that without result.....

**Comment by mw446391** [comment]
Not sure, if this related, but I had noticed on WED evening that PVoutput showed 0 kWh for the whole day; I rebooted my raspi and after a while the generation data for WED showed up.

Also earlier today (maybe an hour ago or so), I noticed that the generation data had flatlined even though it's quite sunny. But without doing anything on my raspi the data eventually showed up.

**Comment by TorpedoBE** [comment]
mine stopped uploading on February 15th without any reason...

If I try /usr/local/bin/sbfspot.3/SBFspot -v -finq -nocsv everthing works fine

in db is everthing stord only uploading to pvoutput doesn't work anymore...

**Comment by mw446391** [comment]
I'm running SBFspot V3.5.2 on the latest version of Raspbian GNU/Linux 9 (stretch) on my Raspberry Pi 3 Model B Rev 1.2 and it works.

**Comment by sbf-** [comment]
V352 uses another upload mechanism

**Comment by TorpedoBE** [comment]
Can I install it on Raspberry pi? in seperate directory?? any manual?

**Comment by mw446391** [comment]
@TorpedoBE what version of SBF are you running? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TorpedoBE** [comment]
I'm running Version 3.1.2.

**Comment by TorpedoBE** [comment]
the problem is that I don't execute the daemon as root....

so if I run 

sudo /usr/local/bin/sbfspot.3/SBFspotUploadDaemon

there is no error in the syslog

but still no upload...

**Comment by TorpedoBE** [comment]
I decided to install another pi with the new version so this issue can be closed.
