### ISSUE TITLE
SBFspot only works for user pi

### ISSUE THREAD

**Issue by HeinvdW** [SBFspot/SBFspot#366]
Hi,

I deleted user pi. However being another user SBPsot can be installed, but not be executed.
It tries to connect through bluetooth but connection is refused by the inverter.
There is a problem with ownershop and group.
I am just a newcomer in Linux so I cannot find a way out other than installing SBFspot under user pi.

Could you change the setup of SBFspot that it can be installed and run under other users as well.

**Comment by sbf-** [comment]
If you are a linux newcomer, why deleting user pi???

**Comment by HeinvdW** [comment]
Security, no name pi present. [https://thepihut.com/blogs/raspberry-pi-tutorials/how-to-change-the-default-account-username-and-password](url)

**Comment by HeinvdW** [comment]
Still, is it correct that SBFspot can only be installed for user pi? 
Or did I miss a setting in the instructions.
[https://github.com/SBFspot/SBFspot/wiki/Installation-Linux-SQLite](url)

**Comment by sbf-** [comment]
No that’s not correct

**Comment by 99technetium** [comment]
I'm running SBFspot on a Debian server and therefore not as the user "pi". I only had to change the directory paths in the default configuration file of SBFspot from "/home/pi/..." to "/home/my_user/..."

**Comment by HeinvdW** [comment]
I tried several times on Pi, also changed all home/pi for home/myuser. Still everything worked, just the BT connection would not connect. Maybe I should have changed permissions for BT user from pi to myuser. Didn't find that in the install instructions.

**Comment by sbf-** [comment]
Show us some output/error messages.
Almost sure it has nothing to do with other username

**Comment by HeinvdW** [comment]
Hi SBF,
You are right. SBFspot can be installed for any user.
I must have overseen something somewhere.
Deleted 3.6.0 and installed it again, carefully following the instructions.
Success!
