### ISSUE TITLE
SBFspot stopped working after upgrading to Raspbian Buster

### ISSUE THREAD

**Issue by jvlerick** [SBFspot/SBFspot#373]
After upgrading my system to buster, SBFspot no longer reports anything to my Domoticz.
When testing by running "/usr/local/bin/sbfspot.3/SBFspot -v -finq -nocsv" I get this error: "error while loading shared libraries: libboost_date_time.so.1.62.0: cannot open shared object file: No such file or directory". 
Apparently with upgrading to Buster libboost version is now 1.67. 
I went through all the installation steps [https://github.com/SBFspot/SBFspot/wiki/Installation-Linux-SQLite](url) again but no change.
Is there any way to solve this or is SBFspot not compatible with Buster?

**Comment by fonske** [comment]
You need to do the recompile SBFspot en SBFspotupload daemon steps again after upgrading to Buster
I had the same issues yesterday.

**Comment by jvlerick** [comment]
I am not very experienced with Linux. Can you explain how to recompile SBFspot? I do not upload data to PVoutput so no need for the SBFspotUploadDaemon

**Comment by sbf-** [comment]
You have a few options:
* Recompile SBFspot from scratch by following the [wiki](https://github.com/SBFspot/SBFspot/wiki/Installation-Linux-SQLite)
* Extracting SBFspot from the [precompiled files](https://github.com/SBFspot/SBFspot/releases/tag/V3.5.2) and replacing the existing SBFspot in /usr/local/bin/sbfspot.3
This executable is statically linked with BOOST 1.66 and doesn't care about installed BOOST version

**Comment by jvlerick** [comment]
Thanks. In the meantime I had indeed already re-installed from scratch. Just going through the steps of the wiki did not work (as mentioned in my first post). So I removed all relevant directories first and started again.

**Comment by deagel** [comment]
hi,
look like #255
