### ISSUE TITLE
Error: SBFSpot: Could not open spot file: with domoticz

### ISSUE THREAD

**Issue by xtrapowa** [SBFspot/SBFspot#375]
Hi there,

I'm still using sbfspot in my old home, now in my new home there is 2 another inverters. I just copy the old cfg file to edit them and now there is the message in my log file " Error: SBFSpot: Could not open spot file". Any idea ? 

Kind regards, 
Thank you, 

Xtra

**Comment by sbf-** [comment]
This is a domoticz error, so better ask there.
