### ISSUE TITLE
SBFspotUpload daemon and MySQL

### ISSUE THREAD

**Issue by 23x7x365** [SBFspot/SBFspot#377]
Hi,
Following an SD card failure, I've just rebuild my SBFspot PI, however I can't get SBFspotUploadDaemon to play nicely with MySQL. I tried the trick of copying the _buster version, however this appears not to have MySQL support, only SQLite. 

Is it possible to provide a working version with MySQL support, or instructions on how to perform a manual build?

Thanks and kind regards,
Richard

**Comment by sbf-** [comment]
I added a precomiled version for buster/mariadb (mysql) to V3.5.2 release
[SBFspotUploadDaemon_buster_mariadb](https://github.com/SBFspot/SBFspot/releases/tag/V3.5.2)
