### ISSUE TITLE
SBF 3.6 / MQTT / Missing Parameter BT-Signal - PdcTot

### ISSUE THREAD

**Issue by obduser** [SBFspot/SBFspot#378]
Hello,

the MQTT support is a great extension, thanks for that!

I noticed that "BT-Signal" and "PdcTot" do not appear in the list of keywords.
Can these still be added?

**Comment by obduser** [comment]
Hello, has "PDCTot" already been integrated as an MQTT-Message ?

**Comment by sbf-** [comment]
@obduser No, I forgot to include it in 3.8
I'll add it to 3.8.1 asap

**Comment by obduser** [comment]
Hello,

thanks for include PDCtot (MQTT), but put the description/parameter of PDCtot in SBFspot.cfg too please.

thx
