### ISSUE TITLE
Where is the online documentation for fine-tuning SBFSpot?

### ISSUE THREAD

**Issue by andreas1974** [SBFspot/SBFspot#383]
The quick reference PDF that can be downloaded from the wiki contains links to an older CodePlex location. It says: 
"For automation and fine-tuning of SBFspot, I refer to the online documentation
(https://sbfspot.codeplex.com/documentation)"
I can't find this documentation on github.

**Comment by sbf-** [comment]
I'm afraid this doc is not moved from codeplex. Don't find it anywhere.
