### ISSUE TITLE
SBFspot can't connect to inverters

### ISSUE THREAD

**Issue by workoft** [SBFspot/SBFspot#385]
Hi,

The two inverters show up when I run hcitool scan, but when I try to use SBFspot, it runs the preset 10 connection attempts and then quits with this message:
`Tue Apr 28 18:20:17 2020: CRITICAL: bthConnect() returned -1`
It doesn't even matter what MAC address I use, I can even just write gibberish there, the behavior is the same - however the automatic installation script does detect them.
The inverters are two SB 3000HF-30. I'm running SBFspot 3.6.0 on a raspberry pi 3B

Thanks

**Comment by sbf-** [comment]
What is the distance between pi and inverters?
Try to move the pi closer.
