### ISSUE TITLE
Inverter serial too large

### ISSUE THREAD

**Issue by brainkiller** [SBFspot/SBFspot#387]
The serial number for a new inverter is to large for the schema.
New inverter number: 3xxxxxxxxx.

I suggest to go for either a bigint or varchar instead of int

**Comment by brainkiller** [comment]
I'm seeing this issue on a MySQL DB

**Comment by sbf-** [comment]
See #330

**Comment by sbf-** [comment]
Since this is related to #330, I'll close this issue.
Will be fixed in next release
