### ISSUE TITLE
Unknown Inverter Type

### ISSUE THREAD

**Issue by DSASDDSD** [SBFspot/SBFspot#389]
Could you please add the following SMA Sunny Boy 4.0-1AV-41 542.

0x000024BB and Inverter Type=SB4.0-1AV-41 542

**Comment by sbf-** [comment]
What version of SBFspot are you running?

**Comment by DSASDDSD** [comment]
I was running an old version 301. Updated to 360 and it's up and running. I was using an older manual I found online. Thanks for the fast reply.
