### ISSUE TITLE
MQTT Username and Password

### ISSUE THREAD

**Issue by HannikMathe** [SBFspot/SBFspot#393]
Is there an option to add MQTT credentials like (username and password) to my MQTT-Broker?

For a very inexperienced person like me, showing at the mqtt.cpp file, it looks simple to add username and password inputs in SBFspot.cfg file.

If I am correct, I'd love to see that feature.

PS: I am so thankful that there are experienced people out there writing code for us dummies. <3

**Comment by sbf-** [comment]
See #380
