### ISSUE TITLE
Simple daily output report

### ISSUE THREAD

**Issue by MrMEScott** [SBFspot/SBFspot#396]
If anyone is interested, I've written a small Python program that generates a graph of the output and total power numbers for a given day. It runs on the headless Raspberry Pi that I've installed SBFspot on. Example attached.
I made this to provide a simple way to see how my system is performing without any external dependencies (e.g. pvoutput.org etc.)

![example](https://user-images.githubusercontent.com/30527614/86248572-fbfed000-bba5-11ea-9afe-82da116618dd.png)

**Comment by saylinglow** [comment]
Funnily enough, I was thinking of doing something similar! Are you willing to share it?

**Comment by MrMEScott** [comment]
Happy to share. It should be pretty self-explanatory to anyone who has a smattering of Python, but otherwise I'd need to write some documentation to explain the few dependencies and how to configure it.

**Comment by MrMEScott** [comment]
Attached is a zip containing the program and a readme file.
[sbfchart.zip](https://github.com/SBFspot/SBFspot/files/4859368/sbfchart.zip)
