### ISSUE TITLE
suggestion for updating wiki

### ISSUE THREAD

**Issue by prein2** [SBFspot/SBFspot#404]
since github doesn't allow me to do a pull request on the wiki page:

In the installation section (https://github.com/SBFspot/SBFspot/wiki/Installation-Linux-SQLite)
All the installation steps are written with the pi username. since not everybody is using the pi username is suggest to change that to: instead of /home/pi/.... use ~/...
so for example this:
cd /home/pi/smadata
sqlite3 SBFspot.db < /home/pi/SBFspot/SBFspot/CreateSQLiteDB.sql

becomes this:
cd ~/smadata
sqlite3 SBFspot.db < ~/SBFspot/SBFspot/CreateSQLiteDB.sql

**Comment by sbf-** [comment]
What about `sudo chown -R pi:pi /var/log/sbfspot.3` ?
Replace by `sudo chown -R $USER:$USER /var/log/sbfspot.3` Will this always work?

**Comment by sbf-** [comment]
Fixed
