### ISSUE TITLE
Unknown Inverter Type 0x00002484 for STP10.0-3AV-40

### ISSUE THREAD

**Issue by hapm** [SBFspot/SBFspot#407]
Tried to add a new STP10.0-3AV-40 and got Unknwon Inverter Type. So i thought I'll report it here.

**Comment by sbf-** [comment]
I guess you're running an older version of SBFspot
STP10.0-3AV-40 is recognized since V3.6.0

**Comment by sbf-** [comment]
See #327

**Comment by hapm** [comment]
Kind of, I forgot to copy the tags list on update.
