### ISSUE TITLE
HowTo: Battery Charge Stats for my ioBroker

### ISSUE THREAD

**Issue by anwelti** [SBFspot/SBFspot#411]
Hello,

i use this setup:
ubuntu 20.04 LTS
iobroker
iobroker sbfspot-4.0-Adapter
sbfspot-3.7 for linux

I want to display my BatteryChargeStatus in ioBroker, but it doesnt get it from spfspot-DB.
How can i transfer this data to my ioBroker?

Thank you all very much.

**Comment by sbf-** [comment]
Don't know anything about ioBroker, sorry. Maybe ask there?

**Comment by anwelti** [comment]
wtf, sorry i think i was on the adapter site from iobroker!
SORRY
