### ISSUE TITLE
PV Output upload data

### ISSUE THREAD

**Issue by mamrai1** [SBFspot/SBFspot#416]
How can I upload grid frequency?
I use spot.Frequency as V11 but nothing...

**Comment by sbf-** [comment]
Use of V11 requires donation to PVO - Is this the case?
Is the frequency available in the db?

**Comment by mamrai1** [comment]
Yes it's available. Is the 'spot.frequency' I used correct or is it
something else?

**Comment by mamrai1** [comment]
It's missing though from 'vwAvgSpotData' table...Should i add it?

**Comment by mamrai1** [comment]
I think that was the problem.. I will check tomorrow when inverter is alive and close the issue if it's working
Thanks

**Comment by mamrai1** [comment]
Works now..
