### ISSUE TITLE
SBFspotUploadDaemon not woking since 5th of Jan

### ISSUE THREAD

**Issue by ced2git** [SBFspot/SBFspot#426]
Hello, 

I've been using SbfspotUploadDaemon for more than a 1 YEAR without any issues but the daemon has stopped to work since the 5th of Jan.

I've restarted my server (rpi zero) and  updated to the latest vesion 3.7.1 but still no luck.

log level is set to debug but nothing is written but the start of the daemon. 

Thanks for youe help

**Comment by sbf-** [comment]
[Here](https://github.com/SBFspot/SBFspot/wiki/No-uploads-to-PVOutput.org) are some tips and tricks

**Comment by ced2git** [comment]
It's solved.... issue with the Plant Time. Weird as i've not suffered any delay so far. 

Thanks anyway for the support.
