### ISSUE TITLE
How to get MQTT working?

### ISSUE THREAD

**Issue by supermarcie** [SBFspot/SBFspot#443]
Hi
I don't find how to get MQTT working.
I configured everything for MQTT, but nothing happens
it looks like it is an extension, but were to find the code?

can someone help me

**Comment by supermarcie** [comment]
I'm bit further.
I installed the moquitto client.
I already have a moqsuitto broker running 

I now get following error:
Error: Invalid port given: 0

I defined the port, also put the port in comment but no difference still get the error

can someone help me?

**Comment by supermarcie** [comment]
it's working but some difficulties to retrieve the MQTT in Home assistant.
Does anyone has this working?

**Comment by sbf-** [comment]
This is more a question for HA forum

**Comment by supermarcie** [comment]
Found out everything, can be closed

**Comment by Twoink** [comment]
> Found out everything, can be closed

Would be nice if you share the solution. I'm facing the same issues at the moment.
Is it possible to check a mqtt log to figure out what is happening?
