### ISSUE TITLE
Small error in SBFspot.V3.Quick.Reference.Linux.EN.1.0.pdf

### ISSUE THREAD

**Issue by roelvdh** [SBFspot/SBFspot#456]
In Testing UploadDeamon:
If all goes well, you should see a logfile in /home/smadata/logs
That doesn't seem right

**Comment by sbf-** [comment]
You are looking in a doc for older SBFspot versions
As from V3.4 you need `SBFspot Installation on Linux with SQLite`
Logging is in `/var/log/sbfspot.3`
