### ISSUE TITLE
Serial number too big for defined field

### ISSUE THREAD

**Issue by diedvdyk** [SBFspot/SBFspot#457]
My serial number is 3xxxxxxxxxxxx . 
I had to alter in all the tables the definition for serial from "Serial int(4) NOT NULL" to  "Serial bigint(4) NOT NULL" because I got errors that my serial number is too big.
I am using Mariadb and I am on 3.7.1

**Comment by stripwax** [comment]
Hm thinking about the actual usecase here, it would probably be better to
have just a small uniqueID int in the tables, and then just one other table
that maps from uniqueID to actual serial number.
The views could the do that via join, but the underlying tables wouldn't
all need to be changed (unless you really owned more than 4 billion
inverters - unlikely!)
Maybe that's how this should be done.  And then the type of the (real)
Serial could be whatever you want (alphanumeric, if necessary) and only one
table would need to be changed.

**Comment by sbf-** [comment]
See #330

**Comment by stripwax** [comment]
Ah indeed, and in particular https://github.com/SBFspot/SBFspot/issues/387
(which is marked Closed due to #330)
