### ISSUE TITLE
Unknown Inverter Type (0x00002484 = SUNNY TRIPOWER 10.0 / STP10.0-3AV-40)

### ISSUE THREAD

**Issue by dpfeilsticker** [SBFspot/SBFspot#458]
Unknown Inverter Type
0x00002484 and Inverter Type = SUNNY TRIPOWER 10.0 / STP10.0-3AV-40

**Comment by sbf-** [comment]
What is the SBFspot version you’re using? The latest should be ok.

**Comment by dpfeilsticker** [comment]
As i have CentOS 7 i was very happy to find a compiled 3.6.0 package (after a hour in self compiling dependency hell):
http://gw.hertle-server.de/adoc/homeautomation/sbfspot/howto.html
Besides the inverter-name this SBFspot 3.6.0 is full functional for me :-)

**Comment by sbf-** [comment]
To fix this, just copy the latest taglist*.txt files over the 3.6.0 version
