### ISSUE TITLE
SBFspot use always multicast socket 9522

### ISSUE THREAD

**Issue by GitStubs** [SBFspot/SBFspot#460]
SBFSPOT 3.8.1 on Raspberry PI 4

OS:
PRETTY_NAME="Linux raspberrypi 4.9.41-v7"

Starting SBFshot via crontab never release the multicast socket (9522/0.0.0.0)
Other programs (i.e. sma-em) are not been able to read multicast messages between.

In your SBFspot.cfg header:

> **# If IP_Address is set to a valid IP, SBFspot will try to connect directly to that IP without broadcast detection**

Not sure why this happens because the IP addresses are permanently assigned in my/the config file (exclusive connection is via speedwire).

**Comment by sbf-** [comment]
Sorry, but I don’t get your point...
