### ISSUE TITLE
Mixing queries for energy and battery inverter in one SBFspot.cfg ...

### ISSUE THREAD

**Issue by GitStubs** [SBFspot/SBFspot#461]
SBFSPOT 3.8.1 on Raspberry PI 4

OS:
PRETTY_NAME="Linux raspberrypi 4.9.41-v7"

... results in zero values for the batterie inverter in the csv file.
If, on the other hand, all queries for the energy inverters are separated from those for the battery inverters, the respective data are correctly summarized in the separate csv files. 

The structure of the output for the energy and battery inverters are completly different.
Therefore it makes sense if the program would split them into different output files on its own.

**Comment by sbf-** [comment]
Can you show an example?
