### ISSUE TITLE
installation Error (bullseye)

### ISSUE THREAD

**Issue by jakkapan-q** [SBFspot/SBFspot#481]
Can't install in on Raspbian11 (bullseye)?

**Comment by sbf-** [comment]
Some more info pls… error message etc

**Comment by jakkapan-q** [comment]
> Some more info pls… error message etc

SBFspot Configuration Tool V1.2.0
Running on Raspberry Pi 3 Model B Rev 1.2
Checking whiptail... Installed.
architecture=armhf
Raspbian GNU/Linux 11 (bullseye)
username=pi
userhome=/home/pi
Error: Unable to get list of available SBFspot versions for 'bullseye'

**Comment by sbf-** [comment]
There’s not yet an official bullseye image, so for now you’ll have to compile SBFspot manually.

**Comment by sbf-** [comment]
Bullseye images added to latest release
