### ISSUE TITLE
WIki Update needed? How to Domoticz

### ISSUE THREAD

**Issue by calberts** [SBFspot/SBFspot#485]
I  was able to install sbfspot

curl -s https://raw.githubusercontent.com/sbfspot/sbfspot-config/master/sbfspot-config | sudo bash

but i have no idea how to get this the information of my SMA in domoticz. I saw that I retrieve info nation in the log files and the SQLLite. Can some help me out

Chris Alberts

**Comment by sbf-** [comment]
Sorry, but I guess you’ll get more help [in domoticz forum](https://www.domoticz.com/forum/viewtopic.php?f=14&t=37046&sid=44bbed9a656db9fdd2cf59b992e00581)
