### ISSUE TITLE
Uninstall 

### ISSUE THREAD

**Issue by srwilli1** [SBFspot/SBFspot#490]
Hi,

I need help to uninstall SBFspot. Unfortunately I haven't found anything about it. I installed it via SBFspot-config

**Comment by sbf-** [comment]
There is no automated solution for uninstalling SBFspot, but if installed in default locations, you can proceed like this:

* Stop upload to PVOutput
```
sudo systemctl stop SBFspotUpload.service
sudo systemctl disable SBFspotUpload.service
```
* Stop SBFspot (edit crontab: remove all SBFspot related entries)
```
crontab -e
```
* Remove executables
```
sudo rm -r /usr/local/bin/sbfspot.3/
```
* Remove log files
```
rm -r /var/log/sbfspot.3/
```
* Remove SQLite database / CSV files
```
rm -r ~/smadata
```
