### ISSUE TITLE
install to debian 11 bullseye

### ISSUE THREAD

**Issue by halfagascan** [SBFspot/SBFspot#498]
curl -s https://raw.githubusercontent.com/sbfspot/sbfspot-config/master/sbfspot-config | sudo bash
SBFspot Configuration Tool V1.2.0
Running on Raspberry Pi 3 Model B Rev 1.2
Checking whiptail... Installed.
architecture=armhf
Raspbian GNU/Linux 11 (bullseye)
username=pi
userhome=/home/pi
Error: Unable to get list of available SBFspot versions for 'bullseye'

**Comment by sbf-** [comment]
Bullseye images added to latest release
