### ISSUE TITLE
compile error sqlite/obj/boost_ext.o

### ISSUE THREAD

**Issue by straybiker** [SBFspot/SBFspot#501]
I am tying to install sbfspot on Debian bullseye, follwing the installation procedure in the Wiki. I am running a linux contrainer on a amd64 platform, so no Pi or ARM.

Running the commande make sqlite give following  error:
make: g++: No such file or directory
make: *** [makefile:117: sqlite/obj/boost_ext.o] Error 127

**Comment by sbf-** [comment]
Did you install `build-essential`?
It looks like c++ compiler is not on your system

**Comment by straybiker** [comment]
Thanks. Problem solved
