### ISSUE TITLE
insert or ignore into inverters error after upgrade to 3.9.0

### ISSUE THREAD

**Issue by lnu** [SBFspot/SBFspot#506]
Hello,

upgraded this morning to 3.9.0 and now I get this in the logs:
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/1829553/147644555-3c9a198d-7f45-4825-99a2-bd3012cc2c32.png">

Never seen this before.

Raspberry pi 2.

**Comment by sbf-** [comment]
Fixed
