### ISSUE TITLE
MQTT / PDCtot / description in SBFspot.cfg

### ISSUE THREAD

**Issue by obduser** [SBFspot/SBFspot#531]
Hello,

thanks for include PDCtot (MQTT), but put the description/parameter of PDCtot in SBFspot.cfg too please.

thx

_Originally posted by @obduser in https://github.com/SBFspot/SBFspot/issues/378#issuecomment-1086817823_

**Comment by sbf-** [comment]
It is [there](https://github.com/SBFspot/SBFspot/blob/master/SBFspot/SBFspot.cfg#L250), no?
