### ISSUE TITLE
SBFspot does not exit when a SIGKILL is send

### ISSUE THREAD

**Issue by freekdk** [SBFspot/SBFspot#536]
Using version 3.9.3 I start SBFspot using the command "timeout -k 30s -s SIGKILL 230s ./SBFspot ...parameters..."
For an unknown reason SBFspot hangs, so it should be killed after 230 seconds and if that fails again after 30 seconds. However it still keeps present and after a while lots of processes are present in the system.

**Comment by silliewimons** [comment]
dear freekdk, can you please provide more details,
 - from experience  when executing sbfspot  to  obtain  the real-time values (spot)  sbfspot will not last more then 3seconds
 - only conditions that sbfspot takes more then 5seconds is when requesting archive options, -ad# daily -am# month  events,
   that type of execution you need in maximum once a day

can you inform the logging information  -d5 -v5  from  an execution where  sbfspot does "hang"
please provide more information about 'scripts' or othe  
please provide the config file

kr  silly

**Comment by freekdk** [comment]
Currently I have the situation again. I am using a Raspberry Pi 2B. The command given is:

timeout -k 30s -s SIGKILL 230s ./SBFspot -d1 -ad7 -v >/tmp/$tmpfile 2>&1

Apparently the problem started at 18:50. So I have the following set of processes:
sma       3817  0.0  0.4   7528  4568 ?        D    18:50   0:00 ./SBFspot -d1 -ad7 -v
sma       3896  0.0  0.4   7528  4568 ?        D    18:55   0:00 ./SBFspot -d1 -ad7 -v
sma       3936  0.0  0.4   7528  4568 ?        D    19:00   0:00 ./SBFspot -d1 -ad7 -v
sma       3986  0.0  0.4   7528  4568 ?        D    19:05   0:00 ./SBFspot -d1 -ad7 -v
sma       4050  0.0  0.4   7528  4568 ?        D    19:10   0:00 ./SBFspot -d1 -ad7 -v
sma       4229  0.0  0.4   7528  4568 ?        D    19:15   0:00 ./SBFspot -d1 -ad7 -v
sma       4269  0.0  0.4   7528  4568 ?        D    19:20   0:00 ./SBFspot -d1 -ad7 -v
sma       4329  0.0  0.4   7528  4568 ?        D    19:25   0:00 ./SBFspot -d1 -ad7 -v
sma       4368  0.0  0.4   7528  4568 ?        D    19:30   0:00 ./SBFspot -d1 -ad7 -v
sma       4407  0.0  0.4   7528  4568 ?        D    19:35   0:00 ./SBFspot -d1 -ad7 -v
sma       4467  0.0  0.4   7528  4568 ?        D    19:40   0:00 ./SBFspot -d1 -ad7 -v
sma       4650  0.0  0.4   7528  4568 ?        D    19:45   0:00 ./SBFspot -d1 -ad7 -v
sma       4690  0.0  0.4   7528  4568 ?        D    19:50   0:00 ./SBFspot -d1 -ad7 -v
sma       4747  0.0  0.4   7528  4568 ?        D    19:55   0:00 ./SBFspot -d1 -ad7 -v
sma       4791  0.0  0.4   7528  4568 ?        D    20:00   0:00 ./SBFspot -d1 -ad7 -v
sma       4839  0.0  0.4   7528  4568 ?        D    20:05   0:00 ./SBFspot -d1 -ad7 -v
sma       4898  0.0  0.4   7528  4568 ?        D    20:10   0:00 ./SBFspot -d1 -ad7 -v
sma       5083  0.0  0.4   7528  4568 ?        D    20:15   0:00 ./SBFspot -d1 -ad7 -v
sma       5124  0.0  0.4   7528  4568 ?        D    20:20   0:00 ./SBFspot -d1 -ad7 -v
sma       5183  0.0  0.4   7528  4568 ?        D    20:25   0:00 ./SBFspot -d1 -ad7 -v
sma       5222  0.0  0.4   7528  4568 ?        D    20:30   0:00 ./SBFspot -d1 -ad7 -v
sma       5261  0.0  0.4   7528  4568 ?        D    20:35   0:00 ./SBFspot -d1 -ad7 -v
sma       5319  0.0  0.4   7528  4568 ?        D    20:40   0:00 ./SBFspot -d1 -ad7 -v
sma       5504  0.0  0.4   7528  4568 ?        D    20:45   0:00 ./SBFspot -d1 -ad7 -v
sma       5546  0.0  0.4   7528  4568 ?        D    20:50   0:00 ./SBFspot -d1 -ad7 -v
sma       5604  0.0  0.4   7528  4568 ?        D    20:55   0:00 ./SBFspot -d1 -ad7 -v
sma       5646  0.0  0.4   7528  4568 ?        D    21:00   0:00 ./SBFspot -d1 -ad7 -v
sma       5695  0.0  0.4   7528  4568 ?        D    21:05   0:00 ./SBFspot -d1 -ad7 -v

Running the same command at this moment gives:
sma@smahp:~/sbfspot393/SBFspot/sqlite/bin> ./SBFspot -d1 -ad7 -v
SBFspot V3.9.3
Yet another tool to read power production of SMA solar inverters
(c) 2012-2022, SBF (https://github.com/SBFspot/SBFspot)
Compiled for Linux (LE) 32 bit with SQLite support
Commandline Args: -d1 -ad7 -v
Reading config '/home/sma/sbfspot393/SBFspot/sqlite/bin/SBFspot.cfg'
Tue May  3 23:19:05 2022: INFO: Starting...
sunrise: 06:08
sunset : 21:08
Nothing to do... it's dark. Use -finq to force inquiry.

Running the command "./SBFspot -d5 -v5", I assume this gives information about the config file, gives:
SBFspot V3.9.3
Yet another tool to read power production of SMA solar inverters
(c) 2012-2022, SBF (https://github.com/SBFspot/SBFspot)
Compiled for Linux (LE) 32 bit with SQLite support
Commandline Args: -d5 -v5
Reading config '/home/sma/sbfspot393/SBFspot/sqlite/bin/SBFspot.cfg'

Configuration settings:
BTAddress=00:80:25:A5:A1:33
MIS_Enabled=0
BTConnectRetries=10
Password=<undisclosed>
Plantname=BornWel
OutputPath=/home/sma/smadata/%Y
OutputPathEvents=/home/sma/smadata/%Y/Events
Latitude=52.0779
Longitude=4.53838
Timezone=Europe/Amsterdam
Locale=nl-NL
CalculateMissingSpotValues=1
DateTimeFormat=%d/%m/%Y %H:%M:%S
DateFormat=%d/%m/%Y
TimeFormat=%H:%M:%S
SynchTime=1
SynchTimeLow=1
SynchTimeHigh=3600
SunRSOffset=0
DecimalPoint=comma
CSV_Delimiter=semicolon
Precision=3
CSV_Export=1
CSV_ExtendedHeader=1
CSV_Header=1
CSV_SaveZeroPower=1
CSV_Spot_TimeSource=0
CSV_Spot_WebboxHeader=0
SQL_Database=/home/sma/smadata/SBFspot.db
End of Config

Tue May  3 23:21:55 2022: INFO: Starting...
sunrise: 06:08
sunset : 21:08
Nothing to do... it's dark. Use -finq to force inquiry.

The command "lsof -p 3817", the first process that hangs, as root, gives:
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
SBFspot 3817  sma  cwd    DIR  179,3     4096 260534 /home/sma/sbfspot393/SBFspot/sqlite/bin
SBFspot 3817  sma  rtd    DIR  179,3     4096      2 /
SBFspot 3817  sma  txt    REG  179,3   358900 260551 /home/sma/sbfspot393/SBFspot/sqlite/bin/SBFspot
SBFspot 3817  sma  mem    REG  179,3  1930356   2533 /usr/lib/libc.so.6
SBFspot 3817  sma  mem    REG  179,3   124724   1245 /usr/lib/libgcc_s.so.1
SBFspot 3817  sma  mem    REG  179,3   360392   2740 /usr/lib/libm.so.6
SBFspot 3817  sma  mem    REG  179,3  1881012  18417 /usr/lib/libstdc++.so.6.0.30
SBFspot 3817  sma  mem    REG  179,3  1244076    501 /usr/lib/libsqlite3.so.0.8.6
SBFspot 3817  sma  mem    REG  179,3     5476   1600 /usr/lib/libboost_system.so.1.78.0
SBFspot 3817  sma  mem    REG  179,3     5480   1454 /usr/lib/libboost_date_time.so.1.78.0
SBFspot 3817  sma  mem    REG  179,3   193616   1436 /usr/lib/libbluetooth.so.3.19.6
SBFspot 3817  sma  mem    REG  179,3   213396   2510 /usr/lib/ld-linux-armhf.so.3
SBFspot 3817  sma    0r  FIFO   0,13      0t0 831817 pipe
SBFspot 3817  sma    1w   REG   0,33      330   1425 /tmp/sbfspotlog.3815 (deleted)
SBFspot 3817  sma    2w   REG   0,33      330   1425 /tmp/sbfspotlog.3815 (deleted)
SBFspot 3817  sma    3u  sock    0,8      0t0 831819 protocol: RFCOMM

I stopped the 5 minutes cron job and will try to gather information when the the SMA is active again in the morning.

**Comment by silliewimons** [comment]
dear freekdk,   thank you for that info,
-remark1:  the options -d5 -v5 are used to enable the full-debug output 
       full-debug-information allows to identify where during execution of the process a "hang" appears
BE CAREFULL - when using these options    because    at each execution, including the succesfull ones, 
      you create  a  large volume of output,

Remember - it is an advantage to capture the execution-flow of a correct execution as well
     in your example - the execution-info  from  sbfspot at 18:40  and  18:45  might be usefull as well
 
-remark2:  about your usage of option -ad7
  -- you instruct sbfspot to collect the daily-table (production) for the past 7days   "each 5minutes" again/again
  -- in general the option -ad7  can be usefull  ONCE a day 
      for the remainder of the day  -ad1 is   more then   sufficient   
      for intraday observation   one uses the information that is written to the spot-table - with 5minute crone-activation

kr  silly

**Comment by freekdk** [comment]
Thanks for the information. I will adapt the script to catch information from earlier missed days; make it more intelligent.
Just tried the -d5 -v5 command. Below is the output. It indicates SBFspot hangs on making the connection with the bluetooth device.

SBFspot V3.9.3
Yet another tool to read power production of SMA solar inverters
(c) 2012-2022, SBF (https://github.com/SBFspot/SBFspot)
Compiled for Linux (LE) 32 bit with SQLite support
Commandline Args: -d5 -v5
Reading config '/home/sma/sbfspot393/SBFspot/sqlite/bin/SBFspot.cfg'

Configuration settings:
BTAddress=00:80:25:A5:A1:33
MIS_Enabled=0
BTConnectRetries=10
Password=<undisclosed>
Plantname=BornWel
OutputPath=/home/sma/smadata/%Y
OutputPathEvents=/home/sma/smadata/%Y/Events
Latitude=52.0779
Longitude=4.53838
Timezone=Europe/Amsterdam
Locale=nl-NL
CalculateMissingSpotValues=1
DateTimeFormat=%d/%m/%Y %H:%M:%S
DateFormat=%d/%m/%Y
TimeFormat=%H:%M:%S
SynchTime=1
SynchTimeLow=1
SynchTimeHigh=3600
SunRSOffset=0
DecimalPoint=comma
CSV_Delimiter=semicolon
Precision=3
CSV_Export=1
CSV_ExtendedHeader=1
CSV_Header=1
CSV_SaveZeroPower=1
CSV_Spot_TimeSource=0
CSV_Spot_WebboxHeader=0
SQL_Database=/home/sma/smadata/SBFspot.db
End of Config

Wed May  4 09:38:31 2022: INFO: Starting...
sunrise: 06:06
sunset : 21:10
Connecting to 00:80:25:A5:A1:33 (1/10)

After this it hangs. I tried, on another terminal, to kill this process, but it fails. I also did unloading and loading again the bluetooth driver, which went OK. Configured it UP again and did a scan for devices, which showed the SMA. See below:

smahp:~ # /sbin/modprobe -r btusb
smahp:~ # /sbin/modprobe -i btusb
smahp:~ # hcitool scan
Device is not available: No such device
smahp:~ # hciconfig hci0 up
smahp:~ # hcitool scan
Scanning ...
        00:80:25:A5:A1:33       SMA001d SN: 2120214953 SN2120214953

**Comment by silliewimons** [comment]
let us recap the status
-a- please inform on inverter type, manufacturing-date    (there is a label on your inverter)
      
-b- this is a stupid question but   ?b?  your system has been operational before?  
      if so - is there any  modification  that you  made   which can be related to this failure

-c- have a look into the sbfspot data generated  during  previous days:  -spot-table;  -daily-file;  -month;  -events 
      that makes certain that there is no earlier "hint" / info / warning / . . . 
      from your config and settings - that info was created at each execution   (path/filename - see your config)
         -- event-info can include warning/errors detected by your inverter 
*** in complement to my earlier remark about the -ad7 option,
         --it is good practice to apply at least two different scripts (crone-tasks)  
             ---once or twice a day (eg. morning&afternoon) to extract system-data  use the default settings 
             ---each 5minutes from sunset-sunrise   with options   -ad1 -am0 -ae0  

-d- abut   hcitool  scan   - from experience  -  that tool captures information
      but it does not give indication about quality / stability of communication/channel   between   Rpi <-> inverter

-e- to control the quality of BT-communication -  please look  into  your sbfspot tables from  previous days,
      there is a column that indicates the BTsignal -       have also a look into the text for  issue 535
          --that issue is about BTconnect - you find a list of items to be controlled  about your inverter and the BT-options

!! the questions above do not explain 'hanging'   but   . . .   

kr  silly

**Comment by sbf-** [comment]
Well, my first action is always a reboot if this kind of issues start to happen.

**Comment by silliewimons** [comment]
thank you for the additional information       
      !!!we are glad that a reboot does remove the 'lock-up'
      but this won't indicate that "cause" of problem is removed                
      to assist in follow up of your issue  it is an advantage to apply v394 (latest version),

-ahaha- we read that you have a long experience using sbfspot,    thank YOU
      from experience, since v308 (2015may), we had 'scarce' issues with hang or BT-issues,
      about config   your previous one is compatible with actual sbfspot version (consult 'default.cfg' for new features)  

your information for BTsignal indicates that   basic communic-channel is OK,

quote your text:    Seeing (10/10) is at 18:45 and (see above) the first one that hangs is at 18:50.
?? so it might be that the "CAUSE" started earlier then 18h45
?? is other software running  that  can  create  a lock-up of a  ?resource?  (either used by sbfspot or . . . .), 
 
about my remark ""once or twice a day (eg. morning&afternoon)" to extract system-data   - term system-data is misleading
   this is about 'best-practice' - with the creation of two distinct executions of sbfspot  
-f- schedule /5 minutes collects the RealTime information -> spot table     (option -ad1 -am0 -ae0 )
-g- schedule once/twice a day collects history information -> previous days / month / events (option -ad7 -am2 -ae1)
      the two executions are complementary  

kr  silly    success

**Comment by freekdk** [comment]
While working on the system the problem occurred. I saw that (10/10) was detected in the log file. There was also a strange process belonging to the sma account. This process was obviously the one that produced the (10/10) text in the log file. Below is the information I got with lsof of that process.

# lsof -p 27072
COMMAND   PID USER   FD      TYPE DEVICE SIZE/OFF NODE NAME
SBFspot 27072  sma  cwd   unknown                      /proc/27072/cwd (readlink: No such file or directory)
SBFspot 27072  sma  rtd   unknown                      /proc/27072/root (readlink: No such file or directory)
SBFspot 27072  sma  txt   unknown                      /proc/27072/exe (readlink: No such file or directory)

This process was killed by timeout, as a message produced by cron, showed.
My script reloaded the bluetooth driver, but still the next invocation of SBFspot was hanging, so the only remedy was a reboot. timeout did try to kill this process, as another message of cron showed, but failed. lsof of this process showed normal information. This has probably nothing to do with SBFspot, so I will prepare a bug report for openSUSE.
In stead for reloading the bluetooth driver I need to do a reboot as a workaround.

**Comment by freekdk** [comment]
The result of the one before the previous invocation of the failing one was normal and OK. The previous one shows a BT Signal=39.6% and the logon fails for an unknown reason and SBFspot returns with a return code of 1. Obviously no data. The failing one gives finally the (10/10), the tenth attempt to connect to the bluetooth device in the log file. This one finishes by the timeout command with return code 137, however this strange process remains. The following one hangs and gives no output in the log file and timeout does not work or any kill -9 of such a process. A kill -9 of the strange process shows a non existing process.

**Comment by silliewimons** [comment]
hello freekdk, 
-?- is there any possible to transfer the results of these last executions, (if executed with -d5 -v5) 
eg. you can attach these as a file, if you give the files a name eg freek & minute-executed then we can distinguish them,

if BTsignal effective drops to 39,6% that is a bad indication  and  might explain why the logon fails,
unless your Rpi has a weak-power unit - there is no reason for this to happen
   
testingBT is not easy - unless you do buy special equipement :-)  
    --for that purpose I do use a windowsPC with a quality BTdongle (usb-BTstick) and the software BTviewer (NirSoft)
         with that software one can observe the stability of the BTsenders  (it is not a measurement)

from my understanding, see your earlier issue314 & 226, you might be using the upload function,  ??is this still the case

kr silly

**Comment by silliewimons** [comment]
hello freekdk,   just to eleminate items,  you have also been involved in issue 512 and 161 as well,
  is there a chance that you are running in that type of problems

even if most of the time (normal conditions) the BTsignal is OK
 - is the distance from your RPi to the inverter short and do they see each other?? 
 - can you move the RPi closer or do you have an USB-cable at hand to put the dongle closer to the inverter
   my experience=: I use a class1 BTdongle - reaches >30meter
         nevertheless by using a USBextension cable I'd move the dongle - within 3meter in front of the inverter
         sincethem - no-failures    24/24  365/365  in operation

kr silly

**Comment by freekdk** [comment]
Still seeing the same problem, but I have some more information.
It looks like it manifests itself shortly before sunset. In the log I see SBFspot reporting a BT Signal=39.6%,  a logon failed, and ends with a return code 1. The next invocation of SBFspot reports 10 times a connection failure and "CRITICAL: bthConnect() returned -1". After this it hangs and timeout tries to kill it, which leaves this strange status of the process. All next invocations between sunrise and sunset are hanging and timeout tries to kill these, which fails, but lsof still shows a rather normal status.

**Comment by silliewimons** [comment]
hello,  please control - is this sunset  or  is this a specifique time = eg 19h40
           please think about any other piece of software/system that migth be activated  (look into the history of the OS)

hello,   please explain  '2 RPis are next to the SMA device'
           is this about one Rpi for your SMA-inverter and the second Rpi for your friend  ??  
           and are these two RPi's  close to each other ??
           or ??? 
till now your information shows that in some manner - the BT-systems get heavily disturbed by . . . .
 - the consequence - login fail ->then-> lock-up-BT   might be related with older-issues

to avoid interference from any other system towards the one under 'debuf'/'supervision' 
- can you (temporary) modify the scheduling (cron) such that the executions at the two systems run at different time-scheme

kr  silly

**Comment by silliewimons** [comment]
hello freekdk:    ahaha 20km distance - so no mutual influence expected    but . . . 

!!IMPORTANT-after rereading my and your comments, i noticed that I did not yet stress this point,
  --BTsignal=strength (reported via sbfspot) - represents "RECEIVE"value == that is quality/level as detected by inverter
    in practice - this is the chain from RPi towards your inverter, -> need to search causes of drop in strength in that chain: 
    -BTunit-in-RPi (eq voltage-drop); -BTinterference(other-senders)(2); -BTpath-blocked/attentuated(2); -BTreceiver-invert(3)
     (*2) items belonging to both directions of the communic.channel
     (*3) SMA has a document that illustrates how signal-strength is influenced by the orientation (front/back left/right)

  --in most systems/setup - that BTsignal strength value  is a valid indication for ~both directions of communication,
  --unfortunate - most (Linux/Wind/. . .) drivers for BTdongles do not deliver a value for the "Receive" part at RPi,
           
-- from experience - there should be NO influence due to low power 'avalaible' from solar-array on "operation" of inverter,
    if your inverter remains connected to the grid, basic functions remain active - needing a few "Watt" from grid
-- this is unless-your-system operates as a "stand-alone" system (island-function) ??which is not your case?? 

-- for your information (by experience) - one ?is/should? able to interrogate an SB 2000HF-30   24/24   <-I can do this :-)
    ---be aware - logically, if you do so, most spot values will be 'ZERO' or 'empty'

kr  slly

**Comment by sbf-** [comment]
> I started with the newest version of openSUSE Tumbleweed

Why don´t you give Raspberry OS lite a try? Now you know almost for sure when it happens.

**Comment by freekdk** [comment]
The situation always occurs after an invocation of SBFspot which gives "BT Signal=39.6%" and gives a return code of 1.
So I noticed this and prevent SBFspot to be invoked until I manually do that. This is what I did next:
sma@smahp:~/sbfspot394/SBFspot/sqlite/bin> ./SBFspot -d5 -v5 -ad${days} -am0 -ae0
SBFspot V3.9.4
Yet another tool to read power production of SMA solar inverters
(c) 2012-2022, SBF (https://github.com/SBFspot/SBFspot)
Compiled for Linux (LE) 32 bit with SQLite support
Commandline Args: -d5 -v5 -ad1 -am0 -ae0
Reading config '/home/sma/sbfspot394/SBFspot/sqlite/bin/SBFspot.cfg'

Configuration settings:
BTAddress=00:80:25:A5:A1:33
MIS_Enabled=0
BTConnectRetries=10
Password=<undisclosed>
Plantname=BornWel
OutputPath=/home/sma/smadata/%Y
OutputPathEvents=/home/sma/smadata/%Y/Events
Latitude=52.0779
Longitude=4.53838
Timezone=Europe/Amsterdam
Locale=nl-NL
CalculateMissingSpotValues=1
DateTimeFormat=%d/%m/%Y %H:%M:%S
DateFormat=%d/%m/%Y
TimeFormat=%H:%M:%S
SynchTime=1
SynchTimeLow=1
SynchTimeHigh=3600
SunRSOffset=0
DecimalPoint=comma
CSV_Delimiter=semicolon
Precision=3
CSV_Export=1
CSV_ExtendedHeader=1
CSV_Header=1
CSV_SaveZeroPower=1
CSV_Spot_TimeSource=0
CSV_Spot_WebboxHeader=0
SQL_Database=/home/sma/smadata/SBFspot.db
End of Config

Thu May 19 09:58:07 2022: INFO: Starting...
sunrise: 05:42
sunset : 21:34
Connecting to 00:80:25:A5:A1:33 (1/10)
Connecting to 00:80:25:A5:A1:33 (2/10)
Connecting to 00:80:25:A5:A1:33 (3/10)
Connecting to 00:80:25:A5:A1:33 (4/10)
Connecting to 00:80:25:A5:A1:33 (5/10)
Connecting to 00:80:25:A5:A1:33 (6/10)
Connecting to 00:80:25:A5:A1:33 (7/10)
Connecting to 00:80:25:A5:A1:33 (8/10)
Connecting to 00:80:25:A5:A1:33 (9/10)
Connecting to 00:80:25:A5:A1:33 (10/10)
Thu May 19 09:58:49 2022: CRITICAL: bthConnect() returned -1
Thu May 19 09:58:49 2022: INFO: Done.

After this the process gets stuck and can't be killed. The process-ID is 30955.

As root:
smahp:~ # lsof -p 30955
COMMAND   PID USER   FD      TYPE DEVICE SIZE/OFF NODE NAME
SBFspot 30955  sma  cwd   unknown                      /proc/30955/cwd (readlink: No such file or directory)
SBFspot 30955  sma  rtd   unknown                      /proc/30955/root (readlink: No such file or directory)
SBFspot 30955  sma  txt   unknown                      /proc/30955/exe (readlink: No such file or directory)

I manage about 10 systems, all running openSUSE. Raspberry OS/Debian is quite different is the answer why I hesitate to use Raspberry OS. Apart from that I am using SBFspot on openSUSE since 2013 without this problem.

**Comment by freekdk** [comment]
I tried to use gdb to find where SBFspot hangs, but I am unable to set a breakpoint in i.e. Inverter.cpp. Apparently I need dbug symbols, but I don't know how to generate these.
I tried with "gdb --directory=../../ ./SBFspot -v -d1 -ad1 -am0 -ae0" and I got the normal output with some extra lines from gdb.

Can you advise me?

**Comment by sbf-** [comment]
Use -g compiler argument
https://stackoverflow.com/questions/89603/how-does-the-debugging-option-g-change-the-binary-executable

**Comment by freekdk** [comment]
I added -g behind:
 CFLAGS     := -c -Wall -O2 -Wno-unused-local-typedefs -Wno-psabi -std=c++11
which became:
 CFLAGS     := -c -Wall -O2 -Wno-unused-local-typedefs -Wno-psabi -std=c++11 -g
and did the compilation again with "make sqlite".
Then I use :
sma@smahp:~/sbfspot394d/SBFspot/sqlite/bin> gdb --directory=../../ --args ./SBFspot -d1 -v -ad1 -am0 -ae0
GNU gdb (GDB; openSUSE Tumbleweed) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "armv7hl-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./SBFspot...
(No debugging symbols found in ./SBFspot)
(gdb) quit

As you can see no debugging symbols. How do I get these in ./SBFspot?

**Comment by sbf-** [comment]
> As you can see no debugging symbols. How do I get these in ./SBFspot?

Remove the -s flag for the linker
`LDFLAGS    :=`

I use Visual Studio for development, so can't help you for the actual debugging with gdb

Maybe it's worth trying to stop SBFspot when it detects a low BT signal?
Something like this:
``` C++
// inverter.cpp
rc = getBT_SignalStrength(m_inverters[0]);
if (VERBOSE_NORMAL) printf("BT Signal=%0.1f%%\n", m_inverters[0]->BT_Signal);

if (m_inverters[0]->BT_Signal < 50.0)
{
    print_error(stdout, PROC_CRITICAL, "BT signal too low\n");
    bthClose();
    return 1;  // Or whatever other error code
}


```

**Comment by freekdk** [comment]
Thanks! That did it. I can use gdb now and can set a breakpoint and step through the program.
When the BT Signal is too low, the program exits with return code 1, so I already use the a test on this return code in the surrounding script to prevent SBFspot to be invoked after this condition. When I see this condition happened, I want to use gdb to step through the program and find out where things go wrong when SBFspot runs again.

**Comment by sbf-** [comment]
> I already use a test on this return code in the surrounding script to prevent SBFspot to be invoked

I know about your script, but what I'm proposing is to change SBFspot with the above code to abort on low BT signal.
So, without login and data retrieval when the signal strength is below e.g. 50%
This way it **might** be possible the connection isn't blocked at the next run.

**Comment by freekdk** [comment]
It still is blocked at the next run. Must be something in the driver/kernel. The problem occurred apparently after an upgrade of the operating system.

**Comment by ghen2** [comment]
FWIW, it's also good practice to prefix (frequent) cronjobs with `flock -n /some/lockfile` to avoid multiple overlapping process instances.  This way it will skip execution if the previous one is still running and holding the lock.
