### ISSUE TITLE
3.9.5 doesn't build

### ISSUE THREAD

**Issue by svde** [SBFspot/SBFspot#544]
See [link](https://build.opensuse.org/package/live_build_log/home:stefan_van_der_eijk/SBFspot/Fedora_35/x86_64).

error: conflicting declaration 'int quiet'

**Comment by sbf-** [comment]
See #543
Will fix it asap

**Comment by sbf-** [comment]
Fixed in [53cc539](https://github.com/SBFspot/SBFspot/commit/53cc5393d633e1040ea2c421545340232bf41f0a)
