### ISSUE TITLE
SBFSpot sometimes sends data to PVOutput with the Voltage not filled in

### ISSUE THREAD

**Issue by ZuinigeRijder** [SBFspot/SBFspot#564]
See also this problem submitted at PVOUTPUT:
https://forum.pvoutput.org/t/pvoutput-getstatus-jsp-regularly-shows-nan-for-voltage-but-intraday-jsp-not/5663/2

SBFSpot sometimes sends data of my SMA inverter to PVOutput with the Voltage not filled in (see examples in bold below). Today 20220826 I saw this already a few times in the SBFSpot logging.

[09:42:34.874] INFO: Uploading datapoint: 20220826,09:40,44749664,384,36.8,234.38 => OK (200)
**[09:48:34.782] INFO: Uploading datapoint: 20220826,09:45,44749699,420 => OK (200)**
[09:53:34.893] INFO: Uploading datapoint: 20220826,09:50,44749739,480,36.9,234.06 => OK (200)
[09:58:34.783] INFO: Uploading datapoint: 20220826,09:55,44749776,444,37,234.3 => OK (200)
[10:04:38.194] INFO: Uploading datapoint: 20220826,10:00,44749798,264,37.1,233.43 => OK (200)
[10:09:35.199] INFO: Uploading datapoint: 20220826,10:05,44749814,192,37.2,231.35 => OK (200)
[10:15:37.990] INFO: Uploading 2 datapoints, starting with 20220826,10:10,44749827,156,37.3,232.01 => OK (200)
[10:20:34.257] INFO: Uploading datapoint: 20220826,10:20,44749858,204,37.4,232.18 => OK (200)
[10:26:38.386] INFO: Uploading datapoint: 20220826,10:25,44749881,276,37.4,232.5 => OK (200)
[10:31:34.213] INFO: Uploading datapoint: 20220826,10:30,44749907,312,37.4,232 => OK (200)
[10:37:38.767] INFO: Uploading datapoint: 20220826,10:35,44749942,420,37.5,232.37 => OK (200)
[10:42:34.662] INFO: Uploading datapoint: 20220826,10:40,44749985,516,37.6,232.4 => OK (200)
**[10:48:37.983] INFO: Uploading datapoint: 20220826,10:45,44750030,540 => OK (200)**
[10:53:34.174] INFO: Uploading datapoint: 20220826,10:50,44750071,492,37.7,232.45 => OK (200)
[10:59:33.795] INFO: Uploading datapoint: 20220826,10:55,44750107,432,37.8,231.92 => OK (200)
[11:04:35.974] INFO: Uploading datapoint: 20220826,11:00,44750141,408,37.9,231.49 => OK (200)

What can be the cause of this? Looks like it occurs regularly, e.g. once per hour. Workarounds?

Using SBFspot V3.9.4 on a Raspberry Pi Model B+ with OS 11 (bullseye)

**Comment by sbf-** [comment]
Have a look in the SBFspot logging and in the vwSpotdata view for that day. I'm almost sure there will be no voltage data available for  these times. When voltage is null, PVoutput takes the previous (last known) value, shown below:

<html>
<body>


Date | Time | Energy | Efficiency | Power | Average | Normalised | Temperature | Voltage | Energy Used | Power Used
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
26/08/22 | 09:45 | 0.525kWh | 0.107kWh/kW | 420W | 420W | 0.086kW/kW | 20.6C | 234.4V | 0.000kWh | -
26/08/22 | 09:40 | 0.490kWh | 0.100kWh/kW | 384W | 384W | 0.078kW/kW | 20.6C | 234.4V | 0.000kWh | -


<br class="Apple-interchange-newline">
</body>
</html>

<html>
<body>


Date | Time | Energy | Efficiency | Power | Average | Normalised | Temperature | Voltage | Energy Used | Power Used
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
26/08/22 | 10:45 | 0.856kWh | 0.175kWh/kW | 540W | 540W | 0.110kW/kW | 20.6C | 232.4V | 0.000kWh | -
26/08/22 | 10:40 | 0.811kWh | 0.166kWh/kW | 516W | 516W | 0.105kW/kW | 20.6C | 232.4V | 0.000kWh | -


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by ZuinigeRijder** [comment]
> Have a look in the SBFspot logging and in the vwSpotdata view for that day. I'm almost sure there will be no voltage data available for these times. When voltage is null, PVoutput takes the previous (last known) value, shown below:
> Date 	Time 	Energy 	Efficiency 	Power 	Average 	Normalised 	Temperature 	Voltage 	Energy Used 	Power Used
> 26/08/22 	09:45 	0.525kWh 	0.107kWh/kW 	420W 	420W 	0.086kW/kW 	20.6C 	234.4V 	0.000kWh 	-
> 26/08/22 	09:40 	0.490kWh 	0.100kWh/kW 	384W 	384W 	0.078kW/kW 	20.6C 	234.4V 	0.000kWh 	-
> 
> Date 	Time 	Energy 	Efficiency 	Power 	Average 	Normalised 	Temperature 	Voltage 	Energy Used 	Power Used
> 26/08/22 	10:45 	0.856kWh 	0.175kWh/kW 	540W 	540W 	0.110kW/kW 	20.6C 	232.4V 	0.000kWh 	-
> 26/08/22 	10:40 	0.811kWh 	0.166kWh/kW 	516W 	516W 	0.105kW/kW 	20.6C 	232.4V 	0.000kWh 	-

I had a look at SBFSpot logging and in vwSpotdata.

> ********************
> * ArchiveDayData() *
> ********************
> startTime: 26/08/2022 00:00:00
> Reading events: 2022-Aug-01
> Fri Aug 26 09:42:09 2022: INFO: Done.
> SBFspot V3.9.4
> Yet another tool to read power production of SMA solar inverters
> (c) 2012-2022, SBF (https://github.com/SBFspot/SBFspot)
> Compiled for Linux (LE) 32 bit with SQLite support
> Commandline Args: -v2 -ad1 -am0 -ae1 -cfg/usr/local/bin/sbfspot.3/SBFspot.cfg
> Reading config '/usr/local/bin/sbfspot.3/SBFspot.cfg'
> Fri Aug 26 09:47:32 2022: INFO: Starting...
> sunrise: 06:47
> sunset : 20:40
> Connecting to 00:80:25:A4:76:9D (1/10)
> Initialising...
> SUSyID: 125 - SessionID: 831863570
> SMA netID=01
> Serial Nr: 7EF614FB (2130056443)
> BT Signal=70.6%
> Logon OK
> Local Host Time: 26/08/2022 09:47:34
> Plant Time     : 26/08/2022 09:47:51 (+17 sec)
> TZ offset      : 3600 sec - DST: On
> Last Time Set  : 30/07/2022 14:04:41
> SUSyID: 138 - SN: 2130056443
> Device Name:      SN: 2130056443
> Device Class:     Solar Inverters
> Device Type:      SB 4000TL-21
> Software Version: 02.10.16.R
> Serial number:    2130056443
> Packet status: 21
> SUSyID: 138 - SN: 2130056443
> Device Status:      Ok
> SUSyID: 138 - SN: 2130056443
> Device Temperature: 36.9Â°C
> SUSyID: 138 - SN: 2130056443
> GridRelay Status:      Closed
> SUSyID: 138 - SN: 2130056443
> Energy Production:
> 	EToday: 0.546kWh
> 	ETotal: 44749.721kWh
> 	Operation Time: 42981.48h
> 	Feed-In Time  : 41516.42h
> SUSyID: 138 - SN: 2130056443
> DC Spot Data:
> 	MPPT 1 Pdc:   0.261kW - Udc: 286.04V - Idc:  0.917A
> 	MPPT 2 Pdc:   0.248kW - Udc: 277.19V - Idc:  0.897A
> 	Calculated Total Pdc:   0.509kW
> AC Spot Data:
> 	Phase 1 Pac :   0.494kW - Uac: 234.06V - Iac:  2.111A
> 	Phase 2 Pac :   0.000kW - Uac:   0.00V - Iac:  0.000A
> 	Phase 3 Pac :   0.000kW - Uac:   0.00V - Iac:  0.000A
> 	Total Pac   :   0.494kW - Calculated Pac:   0.494kW
> 	Efficiency  :   97.05%
> SUSyID: 138 - SN: 2130056443
> Grid Freq. : 49.96Hz
> SUSyID: 138 - SN: 2130056443
> Current Inverter Time: 26/08/2022 09:47:48
> Inverter Wake-Up Time: 26/08/2022 06:55:44
> Inverter Sleep Time  : 26/08/2022 09:47:50


I had a look at the vwSpotData and it appears there is NO data for the Nereast5min for 09:45 and 10:45. Would that be the root cause? Should always the daydata be triggered at exact 5 minutes interval?

```
sqlite> select * from vwSpotdata where TimeStamp LIKE "2022-08-26 09:%" order by TimeStamp;
+---------------------+---------------------+----------------+--------------+------------+------+------+-------+-------+--------+--------+------+------+------+-------+------+------+--------+------+------+--------+--------+------------+--------+----------+-----------+---------------+------------+-----------+--------+-----------+-------------+
|      TimeStamp      |     Nearest5min     |      Name      |     Type     |   Serial   | Pdc1 | Pdc2 | Idc1  | Idc2  |  Udc1  |  Udc2  | Pac1 | Pac2 | Pac3 | Iac1  | Iac2 | Iac3 |  Uac1  | Uac2 | Uac3 | PdcTot | PacTot | Efficiency | EToday |  ETotal  | Frequency | OperatingTime | FeedInTime | BT_Signal | Status | GridRelay | Temperature |
+---------------------+---------------------+----------------+--------------+------------+------+------+-------+-------+--------+--------+------+------+------+-------+------+------+--------+------+------+--------+--------+------------+--------+----------+-----------+---------------+------------+-----------+--------+-----------+-------------+
| 2022-08-26 09:00:13 | 2022-08-26 09:00:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 140  | 134  | 0.493 | 0.5   | 286.02 | 268.8  | 252  | 0    | 0    | 1.082 | 0.0  | 0.0  | 234.09 | 0.0  | 0.0  | 274    | 252    | 92.0       | 260    | 44749434 | 49.96     | 42980.7       | 41515.6    | 70.6      | OK     | Closed    | 36.1        |
| 2022-08-26 09:05:40 | 2022-08-26 09:05:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 194  | 184  | 0.68  | 0.676 | 286.04 | 273.0  | 359  | 0    | 0    | 1.539 | 0.0  | 0.0  | 233.49 | 0.0  | 0.0  | 378    | 359    | 95.0       | 288    | 44749463 | 49.93     | 42980.8       | 41515.7    | 71.0      | OK     | Closed    | 36.2        |
| 2022-08-26 09:11:05 | 2022-08-26 09:10:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 211  | 200  | 0.74  | 0.723 | 286.02 | 277.19 | 393  | 0    | 0    | 1.684 | 0.0  | 0.0  | 233.5  | 0.0  | 0.0  | 411    | 393    | 95.6       | 322    | 44749497 | 49.94     | 42980.9       | 41515.8    | 71.4      | OK     | Closed    | 36.3        |
| 2022-08-26 09:16:31 | 2022-08-26 09:15:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 181  | 171  | 0.635 | 0.637 | 285.22 | 269.6  | 333  | 0    | 0    | 1.43  | 0.0  | 0.0  | 233.03 | 0.0  | 0.0  | 352    | 333    | 94.6       | 353    | 44749528 | 49.92     | 42981.0       | 41515.9    | 70.6      | OK     | Closed    | 36.4        |
| 2022-08-26 09:21:58 | 2022-08-26 09:20:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 183  | 175  | 0.653 | 0.641 | 281.83 | 272.98 | 341  | 0    | 0    | 1.461 | 0.0  | 0.0  | 233.77 | 0.0  | 0.0  | 358    | 341    | 95.3       | 383    | 44749558 | 49.96     | 42981.0       | 41516.0    | 70.6      | OK     | Closed    | 36.5        |
| 2022-08-26 09:27:25 | 2022-08-26 09:25:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 187  | 178  | 0.665 | 0.653 | 281.83 | 272.98 | 346  | 0    | 0    | 1.485 | 0.0  | 0.0  | 234.08 | 0.0  | 0.0  | 365    | 346    | 94.8       | 415    | 44749590 | 49.97     | 42981.1       | 41516.1    | 71.0      | OK     | Closed    | 36.6        |
| 2022-08-26 09:36:38 | 2022-08-26 09:35:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 203  | 193  | 0.724 | 0.718 | 281.81 | 268.78 | 381  | 0    | 0    | 1.629 | 0.0  | 0.0  | 234.2  | 0.0  | 0.0  | 396    | 381    | 96.2       | 470    | 44749644 | 49.99     | 42981.3       | 41516.2    | 71.0      | OK     | Closed    | 36.7        |
| 2022-08-26 09:42:09 | 2022-08-26 09:40:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 221  | 208  | 0.785 | 0.778 | 281.95 | 268.93 | 416  | 0    | 0    | 1.776 | 0.0  | 0.0  | 234.38 | 0.0  | 0.0  | 429    | 416    | 97.0       | 506    | 44749680 | 49.97     | 42981.4       | 41516.3    | 71.0      | OK     | Closed    | 36.8        |
| 2022-08-26 09:47:35 | 2022-08-26 09:50:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 261  | 248  | 0.917 | 0.897 | 286.04 | 277.19 | 494  | 0    | 0    | 2.111 | 0.0  | 0.0  | 234.06 | 0.0  | 0.0  | 509    | 494    | 97.1       | 546    | 44749721 | 49.96     | 42981.5       | 41516.4    | 70.6      | OK     | Closed    | 36.9        |
| 2022-08-26 09:53:01 | 2022-08-26 09:55:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 229  | 217  | 0.794 | 0.79  | 288.89 | 275.82 | 430  | 0    | 0    | 1.836 | 0.0  | 0.0  | 234.3  | 0.0  | 0.0  | 446    | 430    | 96.4       | 591    | 44749765 | 49.96     | 42981.6       | 41516.5    | 71.4      | OK     | Closed    | 37.0        |
| 2022-08-26 09:58:28 | 2022-08-26 10:00:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 122  | 116  | 0.442 | 0.44  | 277.65 | 264.61 | 215  | 0    | 0    | 0.921 | 0.0  | 0.0  | 233.43 | 0.0  | 0.0  | 238    | 215    | 90.3       | 619    | 44749794 | 49.98     | 42981.7       | 41516.6    | 71.0      | OK     | Closed    | 37.1        |
+---------------------+---------------------+----------------+--------------+------------+------+------+-------+-------+--------+--------+------+------+------+-------+------+------+--------+------+------+--------+--------+------------+--------+----------+-----------+---------------+------------+-----------+--------+-----------+-------------+

```

```
sqlite> select * from vwSpotdata where TimeStamp LIKE "2022-08-26 10:%" order by TimeStamp;
+---------------------+---------------------+----------------+--------------+------------+------+------+-------+-------+--------+--------+------+------+------+-------+------+------+--------+------+------+--------+--------+------------+--------+----------+-----------+---------------+------------+-----------+--------+-----------+-------------+
|      TimeStamp      |     Nearest5min     |      Name      |     Type     |   Serial   | Pdc1 | Pdc2 | Idc1  | Idc2  |  Udc1  |  Udc2  | Pac1 | Pac2 | Pac3 | Iac1  | Iac2 | Iac3 |  Uac1  | Uac2 | Uac3 | PdcTot | PacTot | Efficiency | EToday |  ETotal  | Frequency | OperatingTime | FeedInTime | BT_Signal | Status | GridRelay | Temperature |
+---------------------+---------------------+----------------+--------------+------------+------+------+-------+-------+--------+--------+------+------+------+-------+------+------+--------+------+------+--------+--------+------------+--------+----------+-----------+---------------+------------+-----------+--------+-----------+-------------+
| 2022-08-26 10:03:54 | 2022-08-26 10:05:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 108  | 102  | 0.392 | 0.395 | 277.65 | 260.41 | 185  | 0    | 0    | 0.8   | 0.0  | 0.0  | 231.35 | 0.0  | 0.0  | 210    | 185    | 88.1       | 637    | 44749811 | 49.96     | 42981.7       | 41516.7    | 71.0      | OK     | Closed    | 37.2        |
| 2022-08-26 10:09:24 | 2022-08-26 10:10:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 99   | 94   | 0.358 | 0.357 | 277.65 | 264.61 | 165  | 0    | 0    | 0.712 | 0.0  | 0.0  | 232.01 | 0.0  | 0.0  | 193    | 165    | 85.5       | 652    | 44749827 | 49.98     | 42981.8       | 41516.8    | 71.0      | OK     | Closed    | 37.3        |
| 2022-08-26 10:14:44 | 2022-08-26 10:15:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 110  | 105  | 0.4   | 0.392 | 277.65 | 268.8  | 190  | 0    | 0    | 0.822 | 0.0  | 0.0  | 231.49 | 0.0  | 0.0  | 215    | 190    | 88.4       | 667    | 44749841 | 49.98     | 42981.9       | 41516.9    | 71.0      | OK     | Closed    | 37.4        |
| 2022-08-26 10:20:15 | 2022-08-26 10:20:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 129  | 122  | 0.461 | 0.462 | 280.42 | 266.04 | 229  | 0    | 0    | 0.99  | 0.0  | 0.0  | 232.18 | 0.0  | 0.0  | 251    | 229    | 91.2       | 686    | 44749860 | 49.96     | 42982.0       | 41517.0    | 71.0      | OK     | Closed    | 37.4        |
| 2022-08-26 10:25:41 | 2022-08-26 10:25:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 167  | 158  | 0.594 | 0.582 | 281.83 | 272.98 | 307  | 0    | 0    | 1.322 | 0.0  | 0.0  | 232.5  | 0.0  | 0.0  | 325    | 307    | 94.5       | 711    | 44749885 | 50.0      | 42982.1       | 41517.1    | 71.0      | OK     | Closed    | 37.4        |
| 2022-08-26 10:31:13 | 2022-08-26 10:30:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 202  | 191  | 0.71  | 0.703 | 286.04 | 273.0  | 378  | 0    | 0    | 1.633 | 0.0  | 0.0  | 232.0  | 0.0  | 0.0  | 393    | 378    | 96.2       | 741    | 44749916 | 49.96     | 42982.2       | 41517.1    | 71.0      | OK     | Closed    | 37.4        |
| 2022-08-26 10:36:39 | 2022-08-26 10:35:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 274  | 260  | 0.939 | 0.933 | 292.39 | 279.3  | 516  | 0    | 0    | 2.222 | 0.0  | 0.0  | 232.37 | 0.0  | 0.0  | 534    | 516    | 96.6       | 784    | 44749958 | 49.98     | 42982.3       | 41517.2    | 71.0      | OK     | Closed    | 37.5        |
| 2022-08-26 10:42:12 | 2022-08-26 10:40:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 280  | 266  | 0.966 | 0.96  | 290.24 | 277.19 | 528  | 0    | 0    | 2.276 | 0.0  | 0.0  | 232.4  | 0.0  | 0.0  | 546    | 528    | 96.7       | 834    | 44750009 | 49.99     | 42982.4       | 41517.3    | 71.0      | OK     | Closed    | 37.6        |
| 2022-08-26 10:47:39 | 2022-08-26 10:50:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 242  | 230  | 0.848 | 0.83  | 286.02 | 277.19 | 456  | 0    | 0    | 1.961 | 0.0  | 0.0  | 232.45 | 0.0  | 0.0  | 472    | 456    | 96.6       | 880    | 44750054 | 49.96     | 42982.5       | 41517.4    | 70.6      | OK     | Closed    | 37.7        |
| 2022-08-26 10:53:05 | 2022-08-26 10:55:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 214  | 204  | 0.752 | 0.749 | 286.04 | 273.0  | 402  | 0    | 0    | 1.737 | 0.0  | 0.0  | 231.92 | 0.0  | 0.0  | 418    | 402    | 96.2       | 922    | 44750096 | 49.98     | 42982.6       | 41517.5    | 71.4      | OK     | Closed    | 37.8        |
| 2022-08-26 10:58:31 | 2022-08-26 11:00:00 | SN: 2130056443 | SB 4000TL-21 | 2130056443 | 238  | 227  | 0.834 | 0.833 | 286.04 | 273.02 | 450  | 0    | 0    | 1.944 | 0.0  | 0.0  | 231.49 | 0.0  | 0.0  | 465    | 450    | 96.8       | 957    | 44750132 | 49.99     | 42982.7       | 41517.6    | 71.4      | OK     | Closed    | 37.9        |
+---------------------+---------------------+----------------+--------------+------------+------+------+-------+-------+--------+--------+------+------+------+-------+------+------+--------+------+------+--------+--------+------------+--------+----------+-----------+---------------+------------+-----------+--------+-----------+-------------+
```

But why does it then send the following:
[09:48:34.782] INFO: Uploading datapoint: 20220826,09:45,44749699,420 => OK (200)

**Comment by sbf-** [comment]
> Would that be the root cause?

Yes

> Should always the daydata be triggered at exact 5 minutes interval?

More or less at 5min interval, but in your case it runs sometimes 1 or 2 mins later. So it looks like there is an issue with the cron job

> But why does it then send the following:
[09:48:34.782] INFO: Uploading datapoint: 20220826,09:45,44749699,420 => OK (200)

When there is no data in the spotdata table to match with the daydata, SBFspot has nothing to send.

This is my data:
```
sqlite> select timestamp,nearest5min from vwSpotdata where TimeStamp LIKE "2022-08-26 10:%" order by TimeStamp;
2022-08-26 10:00:03|2022-08-26 10:00:00
2022-08-26 10:05:04|2022-08-26 10:05:00
2022-08-26 10:10:04|2022-08-26 10:10:00
2022-08-26 10:15:04|2022-08-26 10:15:00
2022-08-26 10:20:03|2022-08-26 10:20:00
2022-08-26 10:25:03|2022-08-26 10:25:00
2022-08-26 10:30:04|2022-08-26 10:30:00
2022-08-26 10:35:03|2022-08-26 10:35:00
2022-08-26 10:40:04|2022-08-26 10:40:00
2022-08-26 10:45:04|2022-08-26 10:45:00
2022-08-26 10:50:03|2022-08-26 10:50:00
2022-08-26 10:55:03|2022-08-26 10:55:00
```

**Comment by ZuinigeRijder** [comment]
Still strange that data IS send:

> [09:48:34.782] INFO: Uploading datapoint: 20220826,09:45,44749699,420 => OK (200)

Because my external USB bluetooth sometimes stops working, I do a reset. That is why it does not do at at almost exact 5 minutes intervals. I will adapt my script, so the daydata is called at almost exact 5 minutes interval. Therefore this issue can be closed for now. Thanks for the work and help.

**Comment by sbf-** [comment]
> Still strange that data IS send:
> 
> > [09:48:34.782] INFO: Uploading datapoint: 20220826,09:45,44749699,420 => OK (200)

This is by design...
The inverter keeps 5min data for about 62 days (stored in sbfspot.daydata table) and momentary data like ac/dc voltage etc is not kept by the inverter but is stored in sbfspot.spotdata table.
When you are missing the spotdata on a certain 5min interval there is null data for voltage (left join in vwPvoData)
Now, if we don't send the power/generated energy when there is no voltage your PVO graph will be messed up by the gaps.
