### ISSUE TITLE
Can't re-upload data

### ISSUE THREAD

**Issue by jshatch** [SBFspot/SBFspot#579]
Trying to backfill data after being offline for some time, the initial upload worked but I had to delete those outputs on pvoutput and trying to upload them a second time seems to never happen.  Is there a way to force the upload daemon to resubmit data that was already uploaded?

**Comment by sbf-** [comment]
> Is there a way to force the upload daemon to resubmit data that was already uploaded?

In the daydata table, set the pvoutput flag to ´null´ for the records you want to resend

**Comment by jshatch** [comment]
Thank you, that worked.  Apparently I also had to delete the live data, I had only deleted the daily data.
