### ISSUE TITLE
SQL support for battery inverters

### ISSUE THREAD

**Issue by SBFspot** [SBFspot/SBFspot#58]
SBFspot 3.0 stops before data has been written to SQL db
ExportBatteryDataToCSV()
Terminating here... Dealing with Battery Inverter.

See also https://sbfspot.codeplex.com/discussions/565092

#### This work item was migrated from CodePlex
CodePlex work item ID: '52'
Assigned to: 'SBF'
Vote count: '4'

**Comment by sbf-** [comment]
Fixed in V3.4.0
