### ISSUE TITLE
SBF halted on error after update HAS

### ISSUE THREAD

**Issue by FritsOV** [SBFspot/SBFspot#648]
Hello, 
I updated my HAS to the latest version. suddenly sbfspot stops working. I first thought there was an error in the inverter but after investigating it must have something to do with the mqtt. 
I started to notice that after some (2 or 3 ) good connections and writing to pvtoutput.org the system stopped. I deleted sbfspot and restarted my rpi4. reinstalled sbfspot with the propper settings and now getting error 250. 
I also saw before reinstalling error 107 and iirc 110 or 111 passing by. 
I tested with solaroakly on my android and got connection with no problem. I tested with the sunnyexplorer and also no problem. 
Unfortunatly i had to change the default password. 

Energy Production:
	EToday: 18.687kWh
	ETotal: 39860.519kWh
	Operation Time: 50449.10h
	Feed-In Time  : 46013.42h
Packet status: 21
getSpotDCPower returned an error: 21
Packet status: 21
getSpotACPower returned an error: 21
SUSyID: 99 - SN: 1100267652
DC Spot Data:
	MPPT 1 Pdc:   2.310kW - Udc: 331.00V - Idc:  6.980A
	MPPT 2 Pdc:   0.000kW - Udc:   0.00V - Idc:  0.000A
	Calculated Total Pdc:   0.000kW
AC Spot Data:
	Phase 1 Pac :   2.256kW - Uac: 245.00V - Iac:  9.212A
	Phase 2 Pac :   0.000kW - Uac:   0.00V - Iac:  0.000A
	Phase 3 Pac :   0.000kW - Uac:   0.00V - Iac:  0.000A
	Total Pac   :   2.257kW - Calculated Pac:   2.256kW
	Efficiency  :    0.00%
SUSyID: 99 - SN: 1100267652
Grid Freq. : 50.04Hz
SUSyID: 99 - SN: 1100267652
Current Inverter Time: 2023-06-06T16:09:43+0200
Inverter Wake-Up Time: 2023-06-06T16:09:43+0200
Inverter Sleep Time  : 2023-06-06T16:09:43+0200
MQTT: Publishing (HAOS-SBFspot/device) "InvSerial": 1100267652,"InvName": "SN: 1100267652","InvClass": "Solar Inverters","InvType": "SB 3300TL HC","InvSwVer": "12.12.203.R"
Client null sending CONNECT
Connection error: Connection Refused: not authorised.
Error: The connection was refused.
Client null received CONNACK (5)
MQTT: Failed te execute '/usr/bin/mosquitto_pub' mosquitto client installed?
Error 1280 while publishing to MQTT Broker

**and:**
Inverter Wake-Up Time: 2023-06-06T16:09:43+0200
Inverter Sleep Time  : 2023-06-06T16:09:43+0200
MQTT: Publishing (HAOS-SBFspot/device) "InvSerial": 1100267652,"InvName": "SN: 1100267652","InvClass": "Solar Inverters","InvType": "SB 3300TL HC","InvSwVer": "12.12.203.R"
Client null sending CONNECT
Connection error: Connection Refused: not authorised.
Error: The connection was refused.
Client null received CONNACK (5)
MQTT: Failed te execute '/usr/bin/mosquitto_pub' mosquitto client installed?
Error 1280 while publishing to MQTT Broker
********************
* ArchiveDayData() *
********************
startTime: 06/06/2023 00:00:00                      **_<<-------------------- time 00:00:00 is this correct?_**
recv() returned an error: 110
send() returned an error: 107

**Comment by FritsOV** [comment]
on what? it worked. 
MQTT?

**Comment by sbf-** [comment]
Yes. MQTT password.
It worked, but you reinstalled SBFspot...

**Comment by sbf-** [comment]
Test your MQTT connection manually with usr/bin/mosquitto_pub

**Comment by FritsOV** [comment]
just finished with restoring an backup of three days ago from sbfspot. 
After restore at least till now all works again. Have no clue what went wrong....
