### ISSUE TITLE
Support for SUNNY TRIPOWER x.0 SE

### ISSUE THREAD

**Issue by bodomenke** [SBFspot/SBFspot#661]
Hi,

Just installed a SUNNY TRIPOWER 6.0 SE (Hybrid Inverter). Seems that it is not supported by SBFspot:

> Unknown Device Class. Report this issue at https://github.com/SBFspot/SBFspot/issues with following info: 0x00001F49 and Device Class=...    

Any chance to get the new SE inverters supported by SBFspot?

Thanks
Bodo

**Comment by sbf-** [comment]
Hybrid inverters are supported since version 3.9.7
To see the version you have, use SBFspot -?

**Comment by bodomenke** [comment]
Great. Thanks for advice! 
I am on 3.8.4. Unfortunately I do not know how to get a fresh sbfspot image, which runs on Synology, so I will contact nakla/sbfspot and ask to update the repository. 
Many thanks

**Comment by sbf-** [comment]
See also #630
