### ISSUE TITLE
Multiple inverter use, PAC second inverter missing. 

### ISSUE THREAD

**Issue by evertverduin** [SBFspot/SBFspot#663]
Hi all,

I tried to add my second inverter and that works fine. Only issue is that the PAC ( power ac ) from the second inverter is missing.
![image](https://github.com/SBFspot/SBFspot/assets/38087248/71201fb5-30ce-4a33-b750-4dca5a9f3c23)

It is listed in the log output of sbfspot, but not added/mapped to an IDX in domoticz.

DC Spot Data:
<------>MPPT 1 Pdc:   4.137kW - Udc: 417.31V - Idc:  9.914A
<------>MPPT 2 Pdc:   0.000kW - Udc:   0.00V - Idc:  0.000A
<------>Calculated Total Pdc:   4.137kW
AC Spot Data:
<------>Phase 1 Pac :   1.330kW - Uac: 241.89V - Iac:  5.505A
<------>Phase 2 Pac :   1.329kW - Uac: 242.36V - Iac:  5.491A
<------>Phase 3 Pac :   1.334kW - Uac: 242.64V - Iac:  5.508A
**<------>Total Pac   :   3.993kW - Calculated Pac:   3.993kW**  //this one is present as an IDX in domoticz
<------>Efficiency  :   96.52%
SUSyID: 409 - SN: 3011522209
DC Spot Data:
<------>MPPT 1 Pdc:   2.137kW - Udc: 206.22V - Idc: 10.369A
<------>MPPT 2 Pdc:   0.000kW - Udc:   0.00V - Idc:  0.000A
<------>Calculated Total Pdc:   2.137kW
AC Spot Data:
<------>Phase 1 Pac :   2.074kW - Uac: 247.34V - Iac:  8.441A
<------>Phase 2 Pac :   0.000kW - Uac:   0.00V - Iac:  0.000A
<------>Phase 3 Pac :   0.000kW - Uac:   0.00V - Iac:  0.000A
**<------>Total Pac   :   2.074kW - Calculated Pac:   2.074kW**  // this one is not!
<------>Efficiency  :   97.05%
SUSyID: 378 - SN: 3008125508
Grid Freq. : 49.98Hz
SUSyID: 409 - SN: 3011522209
Grid Freq. : 49.97Hz
SUSyID: 378 - SN: 3008125508
Current Inverter Time: 31/08/2023 11:35:02
Inverter Wake-Up Time: 31/08/2023 06:58:56
Inverter Sleep Time  : 31/08/2023 11:35:01
SUSyID: 409 - SN: 3011522209
Current Inverter Time: 31/08/2023 11:35:01
Inverter Wake-Up Time: 31/08/2023 06:57:39
Inverter Sleep Time  : 31/08/2023 11:35:01

Anyone a clue?

Evert

**Comment by sbf-** [comment]
It looks like a Domoticz issue... maybe ask there?
