### ISSUE TITLE
SBFspot V3.4.0 and higher Installation on Linux with SQLite Manual

### ISSUE THREAD

**Issue by Darksplat** [SBFspot/SBFspot#664]
These commands need to be added to the manual if you are install on ubuntu as these commands are not included on a clean install of Ubuntu (22.04.3 LTS)

Installation
Before this step

If you want to build the latest master branch:
`sudo apt install git`

Before the step 

Compile SBFspot with SQLite support:
`sudo apt install make`
`sudo apt install g++`

Configuration
`sudo mkdir /usr/local/bin/sbfspot.3`

Also there is no rc.local under /etc/ - I don't know about this.

Either remove the 'pi' or add the lines below for ubuntu in the config files
/home/....... - add
/home/pi/...... - remove

Cheers

**Comment by sbf-** [comment]
[Fixed](https://github.com/SBFspot/SBFspot/wiki/Installation-Linux-SQLite/_history)
