### ISSUE TITLE
Can SBFspot be setup for Bookworm?

### ISSUE THREAD

**Issue by HeinvdW** [SBFspot/SBFspot#675]
SBFspot isn't prepared for a Bookworm yet.

```
curl -s https://raw.githubusercontent.com/sbfspot/sbfspot-config/master/sbfspot-config | sudo bash
SBFspot Configuration Tool V1.3.4
Running on Raspberry Pi 4 Model B Rev 1.5
Checking whiptail... Installed.
architecture=arm64
Debian GNU/Linux 12 (bookworm)
username=pi
userhome=/home/pi
Error: Unable to get list of available SBFspot versions for 'bookworm'
```

**Comment by sbf-** [comment]
I'm aware of this. See also [issue 67](https://github.com/SBFspot/sbfspot-config/issues/67)

**Comment by sbf-** [comment]
V3.9.7 updated for bookworm

⚠️ New installation command:
`sudo bash -c "$(curl -s https://raw.githubusercontent.com/sbfspot/sbfspot-config/master/sbfspot-config)"`

**Comment by HeinvdW** [comment]
Perfect!
Thanks a lot!
