### ISSUE TITLE
Unable to write to logfile

### ISSUE THREAD

**Issue by Ben1asdfas** [SBFspot/SBFspot#676]
Hello together,

i got problems write the logfiles out of the SBFspotUpload Service.

How do i grant my user or this service rights to write logfiles in the directory /var/log/sbfspot.3 ?

![1](https://github.com/SBFspot/SBFspot/assets/103934660/fe1bd7c8-00ae-4968-a379-a26810ba5543)

**Comment by SBFspot** [comment]
Recent versions of SBFspot (as from 3.9.6) and upload daemon should not write to logfiles anymore

**Comment by Ben1asdfas** [comment]
I installed the latest version as described in the installation guide, where i can check or update ?

**Comment by Ben1asdfas** [comment]
Hi, for cearification, i isntalled version 3.9.7 and it does write log files into /var/log/sbfspot.3

My problem was i used the wrong user to write.

**Comment by sbf-** [comment]
> Recent versions of SBFspot (as from 3.9.6) and upload daemon should not write to logfiles anymore

That's true, but only if `logdir` is removed from `SBFspotUpload.cfg`
