### ISSUE TITLE
CRITICAL: Logon failed. Check 'USER' Password

### ISSUE THREAD

**Issue by peterjgithub** [SBFspot/SBFspot#679]
Hi 

Who can help? Many thanks in advance
**Thu Nov 16 16:23:32 2023: CRITICAL: Logon failed. Check 'USER' Password**

I'm running against the next error, that I can't fix:
```
rpi@raspberry:~ $ /usr/local/bin/sbfspot.3/SBFspot -v -finq -nocsv
SBFspot V3.9.7
Yet another tool to read power production of SMA solar inverters
(c) 2012-2022, SBF (https://github.com/SBFspot/SBFspot)
Compiled for Linux (LE) 32 bit with SQLite support
Commandline Args: -v -finq -nocsv
Reading config '/usr/local/bin/sbfspot.3/SBFspot.cfg'
Thu Nov 16 16:23:28 2023: INFO: Starting...
sunrise: 08:04
sunset : 16:56
Connecting to xx:xx:xx:xx:57:92 (1/15)
Initialising...
SUSyID: 125 - SessionID: 922909956
SMA netID=09
Serial Nr: 7D2FDAE7 (2100288231)
BT Signal=67.8%
Thu Nov 16 16:23:32 2023: CRITICAL: Logon failed. Check 'USER' Password
Thu Nov 16 16:23:32 2023: INFO: Done.
```
**My logbook:**

1. I followed all steps on https://github.com/SBFspot/SBFspot/wiki/Installation-Linux-SQLite manually, not through [sbfspot-config](https://github.com/SBFspot/sbfspot-config)

- Installation: perfect, no errors
- Database setup: perfect: no errors
- Configuration:  perfect: no errors, see config file detailed further

2. I ran bluetoothctl and paired succesfully with xx:xx:xx:xx:57:92
=> I'm sure it can be connected and password is correct (it is still the default)

3. I tried to reinstall using a docker file, same error

4. I tried to reinstall with [sbfspot-config](https://github.com/SBFspot/sbfspot-config) : same error

5. I tried with -installer -password:1111 => same error

**My configuration:**
- hardware: raspberry pi v3B
- OS: raspberry pi light, installed with raspberry imager, with apt full-upgrade
- using eth0 (LAN, not wifi), fixed ip
- this inverter: SMA009d  SN: 2100288231  model SB 3000TL
(installed in 2011: 2x SB 3000TL-20 and a SB 4000TL-20)

no daemon running yet (I tried, didnt make a difference)
password only contains numbers, it doess not contain a "!"
I have no Sunny Explorer, so it cannot interfere. 
There is no other process communicating with the inverters.

**SBFspot.cfg**
```
BTAddress=xx:xx:xx:xx:57:92 (xx is replaced here, not in config file)
#LocalBTAddress=00:00:00:00:00:00 (I have 3 inverters, but I would be happy to see SBFspot working wit 1, I can add the 2 others later)
Password=xxxx (xx is replaced here, not in config file)
MIS_Enabled=0
Plantname=Goudvink9
OutputPath=/home/pi/smadata/%Y
OutputPathEvents=/home/pi/smadata/%Y/Events
Latitude=50.xxxxxxxxxxxxx (xx is replaced here, not in config file)
Longitude=3.xxxxxxxxxxxxx (xx is replaced here, not in config file)
CalculateMissingSpotValues=1
DateTimeFormat=%d/%m/%Y %H:%M:%S
DateFormat=%d/%m/%Y
DecimalPoint=comma
TimeFormat=%H:%M:%S
SynchTime=7
SynchTimeLow=60
SynchTimeHigh=3600
SunRSOffset=900
Locale=nl-NL
Timezone=Europe/Brussels
BTConnectRetries=15
CSV_Export=1
CSV_ExtendedHeader=1
CSV_Header=1
CSV_SaveZeroPower=1
CSV_Delimiter=semicolon
CSV_Spot_TimeSource=Inverter
CSV_Spot_WebboxHeader=0
SQL_Database=/home/pi/smadata/SBFspot.db
MQTT_Publisher=/usr/bin/mosquitto_pub
MQTT_Host=test.mosquitto.org
MQTT_Topic=sbfspot_{serial}
MQTT_ItemFormat="{key}": {value}
MQTT_ItemDelimiter=comma
MQTT_PublisherArgs=-h {host} -t {topic} -r -m "{{message}}"
MQTT_Data=Timestamp,SunRise,SunSet,InvSerial,InvName,InvTime,InvStatus,InvTempe>
```

**Comment by SBFspot** [comment]
> 2\. I ran bluetoothctl and paired succesfully with xx:xx:xx:xx:57:92
>     => I'm sure it can be connected and password is correct (it is still the default)

Don’t get this step… pairing is not needed.
Since you don’t have/use sunnyexplorer SW you can’t change the password.
