### ISSUE TITLE
Update to 3.9.8 failed

### ISSUE THREAD

**Issue by wokkeltje13** [SBFspot/SBFspot#686]
![image](https://github.com/SBFspot/SBFspot/assets/57153640/03fcf6d4-d0f6-4d16-bfd3-059c6347247b)

![image](https://github.com/SBFspot/SBFspot/assets/57153640/b2a8e931-8e62-4418-8dab-09494d316664)

previous updates installed OK.
Any idea how I can troubleshoot?

**Comment by wokkeltje13** [comment]
Installing 3.9.7 has no issue 
sudo bash -c "$(curl -s https://raw.githubusercontent.com/sbfspot/sbfspot-config/master/sbfspot-config)" -s 3.9.7

**Comment by sbf-** [comment]
Have you tried multiple times? I installed it on new bullseye 32bit without issues.

After installation of 3.9.8 you can run it manually to see more output:
`/usr/local/bin/sbfspot.3/SBFspot -finq -v5`

**Comment by wokkeltje13** [comment]
I receive "Illegal instruction", nothing more.
Tried multiple times on a rPi Zero W
Operating System: Raspbian GNU/Linux 11 (bullseye)
Kernel: Linux 6.1.21+
Architecture: arm

**Comment by sbf-** [comment]
Binaries were compiled for `arm32v7` instead of `arm32v6`
Should run on RPi zero now

**Comment by wokkeltje13** [comment]
tnx, this solved the issue.
