### ISSUE TITLE
Feature request: make it a service or let the UploadService call it before upload

### ISSUE THREAD

**Issue by SBFspot** [SBFspot/SBFspot#69]
Please vote if you want this feature request to be implemented

#### This work item was migrated from CodePlex
CodePlex work item ID: '64'
Vote count: '3'

**Comment by SBFspot** [comment]
[brunofabre@31/10/2014]
Yes should be a service just like the UploadService.

**Comment by PjotrekSE** [comment]
I (think) I have a working solution in my SBFspot repository, although only for Linux, specifically tested in Raspberry Pi.
@sbf : See pm.

**Comment by sbf-** [comment]
See #318
