### ISSUE TITLE
error compiling on recent Armbian / arm debian with mariadb reference to deprecated include <mysql/mysql.h>

### ISSUE THREAD

**Issue by kbuggenhout** [SBFspot/SBFspot#695]
on current version compilation breaks not finding <mysql/mysql.h> in db_MySQL.h , compiling with mariadb.
fix : change line : 41  #include <mysql/mysql.h> to #include < mariadb/mysql.h>

**Comment by sbf-** [comment]
Create a symlink when using MariaDB:

`sudo ln -s /usr/include/mariadb /usr/include/mysql`

**Comment by sbf-** [comment]
[Wiki](https://github.com/SBFspot/SBFspot/wiki/Installation-Linux-MySQL-%7C-MariaDB) updated
