### ISSUE TITLE
better_sqlite3.node'was compiled against a different Node.js version

### ISSUE THREAD

**Issue by runrennerrun** [SBFspot/SBFspot#707]
Hi All , 

I am getting the following error after updating all with apt-upgrade:

> "exception in DB_Connect [Error: The module '/opt/iobroker/node_modules/better-sqlite3/build/Release/better_sqlite3.node'was compiled against a different Node.js version usingNODE_MODULE_VERSION 108. This version of Node.js requiresNODE_MODULE_VERSION 115. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`).]"

Can you give me a hint how to solve this?

**Comment by sbf-** [comment]
Sorry, this is not an SBFspot issue.
I guess you can get help [here](https://github.com/rg-engineering/ioBroker.sbfspot)
Good luck, this issue will be closed.
